// Generated by fastfk for robot: six_dof
// Task: spatial:link4[0]; spatial:link4[1]; spatial:link4[2]; spatial:link4[3]; spatial:link4[4]; spatial:link4[5]
#include "fk_jacobian.hpp"

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: link4
  {
  double fk_s33 = 0, fk_c32 = 0;
  fastfk_fast_sincos(q[0], &fk_s33, &fk_c32);
  const double r0 = fk_c32;
  double fk_s37 = 0, fk_c36 = 0;
  fastfk_fast_sincos(q[1], &fk_s37, &fk_c36);
  const double r3 = fk_c36;
  const double t96 = (fk_s33 * r3);
  const double t107 = ((fk_s33) * (0.14999999999999999) + ((t96 * 0.14999999999999999)));
  const double t93 = (-(fk_s37));
  double fk_s46 = 0, fk_c45 = 0;
  fastfk_fast_sincos(q[2], &fk_s46, &fk_c45);
  const double r7 = fk_c45;
  const double t101 = (t93 * r7);
  const double t114 = ((t93) * (0.14999999999999999) + ((t101 * 0.12)));
  const double t110 = ((t96) * (r7) + ((r0 * fk_s46)));
  const double t113 = ((t110) * (0.12) + (t107));
  const double r2 = (-(fk_s33));
  const double t97 = (fk_s33 * fk_s37);
  const double r5 = (r0 * r3);
  const double t106 = ((r0) * (0.14999999999999999) + ((r5 * 0.14999999999999999)));
  const double r13 = ((r5) * (r7) + ((r2 * fk_s46)));
  const double t112 = ((r13) * (0.12) + (t106));
  const double r6 = (r0 * fk_s37);
  const double r9 = (-(fk_s46));
  const double t102 = (t93 * r9);
  double fk_s69 = 0, fk_c68 = 0;
  fastfk_fast_sincos(q[3], &fk_s69, &fk_c68);
  const double r11 = fk_s69;
  const double t120 = ((t101) * (r11) + ((r3 * fk_c68)));
  const double r12 = (-(r11));
  const double t119 = ((t101) * (fk_c68) + ((r3 * r12)));
  const double r14 = ((r5) * (r9) + ((r2 * r7)));
  const double r15 = ((t96) * (r9) + ((r0 * r7)));
  const double t115 = ((r13) * (fk_c68) + ((r6 * r12)));
  const double t116 = ((r13) * (r11) + ((r6 * fk_c68)));
  const double t117 = ((t110) * (fk_c68) + ((t97 * r12)));
  const double t118 = ((t110) * (r11) + ((t97 * fk_c68)));
  R[0] = t115;
  R[1] = r14;
  R[2] = t116;
  R[3] = t117;
  R[4] = r15;
  R[5] = t118;
  R[6] = t119;
  R[7] = t102;
  R[8] = t120;
  p[0] = t112;
  p[1] = t113;
  p[2] = t114;
  // Jacobian (6 x 6)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  const double t122 = (0 - t113);
  const double t125 = ((r2) * ((t113 - (fk_s33 * 0.14999999999999999))) + ((-((r0 * (t112 - (r0 * 0.14999999999999999)))))));
  const double t123 = (r0 * t114);
  const double t124 = (0 - (r2 * t114));
  const double t128 = ((r6) * ((t113 - t107)) + ((-((t97 * (t112 - t106))))));
  const double t121 = (t114 - (t93 * 0.14999999999999999));
  const double t126 = ((t97) * (t121) + ((-((r3 * (t113 - t107))))));
  const double t127 = ((r3) * ((t112 - t106)) + ((-((r6 * t121)))));
  const double t131 = ((r14) * ((t113 - t113)) + ((-((r15 * (t112 - t112))))));
  const double t129 = ((r15) * ((t114 - t114)) + ((-((t102 * (t113 - t113))))));
  const double t130 = ((t102) * ((t112 - t112)) + ((-((r14 * (t114 - t114))))));
  J[0 * 6 + 0] = ((t115) * (t122) + ((t117 * t112)));
  J[0 * 6 + 1] = ((t119) * (t125) + (((t115) * (t123) + ((t117 * t124)))));
  J[0 * 6 + 2] = ((t119) * (t128) + (((t115) * (t126) + ((t117 * t127)))));
  J[0 * 6 + 3] = ((t119) * (t131) + (((t115) * (t129) + ((t117 * t130)))));
  J[1 * 6 + 0] = ((r14) * (t122) + ((r15 * t112)));
  J[1 * 6 + 1] = ((t102) * (t125) + (((r14) * (t123) + ((r15 * t124)))));
  J[1 * 6 + 2] = ((t102) * (t128) + (((r14) * (t126) + ((r15 * t127)))));
  J[1 * 6 + 3] = ((t102) * (t131) + (((r14) * (t129) + ((r15 * t130)))));
  J[2 * 6 + 0] = ((t116) * (t122) + ((t118 * t112)));
  J[2 * 6 + 1] = ((t120) * (t125) + (((t116) * (t123) + ((t118 * t124)))));
  J[2 * 6 + 2] = ((t120) * (t128) + (((t116) * (t126) + ((t118 * t127)))));
  J[2 * 6 + 3] = ((t120) * (t131) + (((t116) * (t129) + ((t118 * t130)))));
  J[3 * 6 + 0] = t119;
  J[3 * 6 + 1] = ((t115) * (r2) + ((t117 * r0)));
  J[3 * 6 + 2] = ((t119) * (r3) + (((t115) * (r6) + ((t117 * t97)))));
  J[3 * 6 + 3] = ((t119) * (t102) + (((t115) * (r14) + ((t117 * r15)))));
  J[4 * 6 + 0] = t102;
  J[4 * 6 + 1] = ((r14) * (r2) + ((r15 * r0)));
  J[4 * 6 + 2] = ((t102) * (r3) + (((r14) * (r6) + ((r15 * t97)))));
  J[4 * 6 + 3] = ((t102) * (t102) + (((r14) * (r14) + ((r15 * r15)))));
  J[5 * 6 + 0] = t120;
  J[5 * 6 + 1] = ((t116) * (r2) + ((t118 * r0)));
  J[5 * 6 + 2] = ((t120) * (r3) + (((t116) * (r6) + ((t118 * t97)))));
  J[5 * 6 + 3] = ((t120) * (t102) + (((t116) * (r14) + ((t118 * r15)))));
  }
}
#ifdef __cplusplus
}
#endif

