#pragma once
// Generated by fastfk for robot: six_dof
// Task: spatial:link4[0]; spatial:link4[1]; spatial:link4[2]; spatial:link4[3]; spatial:link4[4]; spatial:link4[5]
// FASTFK_TASK_ABI: spatial_local
// FASTFK_CODEGEN: sincos,fast-trig,no-fma,min-regs,budget=16,share=cost-aware
// FASTFK_CXX_FLAGS: -O2 -std=c++17 -march=native -ffp-contract=off
#include <cmath>
#include "fk_fast_math.hpp"
#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R /*[9]*/,
    double* p /*[3]*/,
    double* J /*[6 x 6] row-major*/);
#ifdef __cplusplus
}
#endif
