#pragma once
// Generated by fastfk for robot: panda_arm
// Task: spatial:panda_link3[0]; spatial:panda_link3[1]; spatial:panda_link3[2]; spatial:panda_link3[3]; spatial:panda_link3[4]; spatial:panda_link3[5]
// FASTFK_TASK_ABI: spatial_local
// FASTFK_CODEGEN: sincos,fast-trig,no-fma,min-regs,budget=16,share=cost-aware
// FASTFK_CXX_FLAGS: -O2 -std=c++17 -march=native -ffp-contract=off
#include <cmath>
#include "fk_fast_math.hpp"
#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R /*[9]*/,
    double* p /*[3]*/,
    double* J /*[6 x 7] row-major*/);
#ifdef __cplusplus
}
#endif
