// Generated by fastfk for robot: panda_arm
// Task: spatial:panda_link3[0]; spatial:panda_link3[1]; spatial:panda_link3[2]; spatial:panda_link3[3]; spatial:panda_link3[4]; spatial:panda_link3[5]
#include "fk_jacobian.hpp"

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: panda_link3
  {
  double fk_s40 = 0, fk_c39 = 0;
  fastfk_fast_sincos(q[0], &fk_s40, &fk_c39);
  const double r0 = fk_c39;
    double fk_s44 = 0, fk_c43 = 0;
    fastfk_fast_sincos(q[1], &fk_s44, &fk_c43);
  const double t61 = (-(fk_s44));
  const double t63 = (fk_s40 * t61);
  const double t69 = (((-(fk_c43))) * (-0.316) + (0.33300000000000002));
  const double r4 = (r0 * t61);
  const double t67 = (r4 * -0.316);
  const double r2 = (-(fk_s40));
  const double t68 = (t63 * -0.316);
  double fk_s54 = 0, fk_c53 = 0;
  fastfk_fast_sincos(q[2], &fk_s54, &fk_c53);
  const double r5 = fk_c53;
  const double r7 = (-(fk_s54));
  const double t77 = (t61 * r7);
  const double t73 = (((fk_s40 * fk_c43)) * (r5) + ((r0 * fk_s54)));
  const double r8 = (((r0 * fk_c43)) * (r5) + ((r2 * fk_s54)));
  const double r9 = (((r0 * fk_c43)) * (r7) + ((r2 * r5)));
  const double r10 = (-(r4));
  const double r11 = (((fk_s40 * fk_c43)) * (r7) + ((r0 * r5)));
  const double r12 = (-(t63));
  const double r13 = (t61 * r5);
  R[0] = r8;
  R[1] = r9;
  R[2] = r10;
  R[3] = t73;
  R[4] = r11;
  R[5] = r12;
  R[6] = r13;
  R[7] = t77;
  R[8] = fk_c43;
  p[0] = t67;
  p[1] = t68;
  p[2] = t69;
  // Jacobian (6 x 7)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  const double t80 = (0 - t68);
  const double t81 = ((r2) * (t68) + ((-((r0 * t67)))));
  const double t78 = (r0 * (t69 - 0.33300000000000002));
  const double t79 = (0 - (r2 * (t69 - 0.33300000000000002)));
  const double t82 = ((t63) * (-0.316) + ((-(t68))));
  const double t83 = ((r4) * (-0.316) + ((-(t67))));
  const double t84 = ((r10) * (t82) + ((-((r12 * t83)))));
  const double t85 = ((r12) * ((t69 - t69)) + ((-((fk_c43 * t82)))));
  const double t86 = ((fk_c43) * (t83) + ((-((r10 * (t69 - t69))))));
  J[0 * 7 + 0] = ((r8) * (t80) + ((t73 * t67)));
  J[0 * 7 + 1] = ((r13) * (t81) + (((r8) * (t78) + ((t73 * t79)))));
  J[0 * 7 + 2] = ((r13) * (t84) + (((r8) * (t85) + ((t73 * t86)))));
  J[1 * 7 + 0] = ((r9) * (t80) + ((r11 * t67)));
  J[1 * 7 + 1] = ((t77) * (t81) + (((r9) * (t78) + ((r11 * t79)))));
  J[1 * 7 + 2] = ((t77) * (t84) + (((r9) * (t85) + ((r11 * t86)))));
  J[2 * 7 + 0] = ((r10) * (t80) + ((r12 * t67)));
  J[2 * 7 + 1] = ((fk_c43) * (t81) + (((r10) * (t78) + ((r12 * t79)))));
  J[2 * 7 + 2] = ((fk_c43) * (t84) + (((r10) * (t85) + ((r12 * t86)))));
  J[3 * 7 + 0] = r13;
  J[3 * 7 + 1] = ((r8) * (r2) + ((t73 * r0)));
  J[3 * 7 + 2] = ((r13) * (fk_c43) + (((r8) * (r10) + ((t73 * r12)))));
  J[4 * 7 + 0] = t77;
  J[4 * 7 + 1] = ((r9) * (r2) + ((r11 * r0)));
  J[4 * 7 + 2] = ((t77) * (fk_c43) + (((r9) * (r10) + ((r11 * r12)))));
  J[5 * 7 + 0] = fk_c43;
  J[5 * 7 + 1] = ((r10) * (r2) + ((r12 * r0)));
  J[5 * 7 + 2] = ((fk_c43) * (fk_c43) + (((r10) * (r10) + ((r12 * r12)))));
  }
}
#ifdef __cplusplus
}
#endif

