// Generated by fastfk for robot: skew_axis
// Task: spatial:link1[0]; spatial:link1[1]; spatial:link1[2]; spatial:link1[3]; spatial:link1[4]; spatial:link1[5]
#include "fk_jacobian.hpp"

// q-invariant R/p (call once; not written by fastfk_task).
void fastfk_init_static_frames(double* R, double* p) {
  // link1
  p[0] = 0.20000000000000001;
  p[1] = 0.0;
  p[2] = 0.0;
}

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: link1
  {
  double fk_s15 = 0, fk_c14 = 0;
  fastfk_fast_sincos(q[0], &fk_s15, &fk_c14);
  const double r0 = fk_c14;
  const double r1 = ((1 - r0) * 0.49999999999999989);
  const double r2 = (0.70710678118654746 * fk_s15);
  const double r3 = (-0.70710678118654746 * fk_s15);
  const double r4 = (((1 - r0)) * (0.49999999999999989) + (r0));
  R[0] = r4;
  R[1] = r1;
  R[2] = r2;
  R[3] = r1;
  R[4] = r4;
  R[5] = r3;
  R[6] = r3;
  R[7] = r2;
  R[8] = r0;
  // Jacobian (6 x 2)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  J[3 * 2 + 0] = ((r4) * (0.70710678118654746) + ((r1 * 0.70710678118654746)));
  J[4 * 2 + 0] = ((r1) * (0.70710678118654746) + ((r4 * 0.70710678118654746)));
  J[5 * 2 + 0] = ((r2) * (0.70710678118654746) + ((r3 * 0.70710678118654746)));
  }
}
#ifdef __cplusplus
}
#endif

