// Generated by fastfk for robot: panda_arm
// Task: spatial:panda_link4[0]; spatial:panda_link4[1]; spatial:panda_link4[2]; spatial:panda_link4[3]; spatial:panda_link4[4]; spatial:panda_link4[5]
#include "fk_jacobian.hpp"

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: panda_link4
  {
  double fk_s40 = 0, fk_c39 = 0;
  fastfk_fast_sincos(q[0], &fk_s40, &fk_c39);
  const double r0 = fk_c39;
  double fk_s44 = 0, fk_c43 = 0;
  fastfk_fast_sincos(q[1], &fk_s44, &fk_c43);
  const double r3 = fk_c43;
  const double t22 = (-(r3));
  const double t8 = (fk_s40 * r3);
  double fk_s54 = 0, fk_c53 = 0;
  fastfk_fast_sincos(q[2], &fk_s54, &fk_c53);
  const double r8 = fk_s54;
  const double r9 = (-(r8));
  const double t16 = (r0 * fk_c53);
  const double t28 = ((t8) * (r9) + (t16));
  const double r5 = (-(fk_s44));
  const double t31 = (r5 * r9);
  const double r6 = (r0 * r3);
  const double r2 = (-(fk_s40));
  const double t13 = (r2 * r8);
  const double r14 = ((r6) * (fk_c53) + (t13));
  const double t32 = (r14 * 0.082500000000000004);
  const double t15 = (r0 * r8);
  const double t27 = ((t8) * (fk_c53) + (t15));
  const double t34 = (t27 * 0.082500000000000004);
  const double t30 = (r5 * fk_c53);
  const double t23 = ((t22) * (-0.316) + (0.33300000000000002));
  const double t36 = ((t30) * (0.082500000000000004) + (t23));
  double fk_s79 = 0, fk_c78 = 0;
  fastfk_fast_sincos(q[3], &fk_s79, &fk_c78);
  const double r12 = fk_s79;
  const double t47 = (r3 * r12);
  const double t49 = (r3 * fk_c78);
  const double t9 = (fk_s40 * r5);
  const double t29 = (-(t9));
  const double r10 = (r2 * fk_c53);
  const double t25 = ((r6) * (r9) + (r10));
  const double t7 = (r0 * r5);
  const double t35 = ((t9) * (-0.316) + (t34));
  const double t33 = ((t7) * (-0.316) + (t32));
  const double t48 = ((t30) * (fk_c78) + (t47));
  const double t26 = (-(t7));
  const double t51 = (-(t31));
  const double t37 = (t26 * r12);
  const double t39 = (t26 * fk_c78);
  const double t41 = (-(t25));
  const double r13 = (-(r12));
  const double t50 = ((t30) * (r13) + (t49));
  const double r15 = ((r14) * (fk_c78) + (t37));
  const double t40 = ((r14) * (r13) + (t39));
  const double t42 = (t29 * r12);
  const double t44 = (t29 * fk_c78);
  const double t46 = (-(t28));
  const double t43 = ((t27) * (fk_c78) + (t42));
  const double t45 = ((t27) * (r13) + (t44));
  R[0] = r15;
  R[1] = t40;
  R[2] = t41;
  R[3] = t43;
  R[4] = t45;
  R[5] = t46;
  R[6] = t48;
  R[7] = t50;
  R[8] = t51;
  p[0] = t33;
  p[1] = t35;
  p[2] = t36;
  // Jacobian (6 x 7)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  const double t58 = (0 - t35);
  const double t59 = (t43 * t33);
  const double t60 = ((r15) * (t58) + (t59));
  const double t65 = (r0 * t33);
  const double t66 = (-(t65));
  const double t67 = ((r2) * (t35) + (t66));
  const double t52 = (t36 - 0.33300000000000002);
  const double t55 = (r0 * t52);
  const double t56 = (r2 * t52);
  const double t57 = (0 - t56);
  const double t90 = (t43 * t57);
  const double t91 = ((r15) * (t55) + (t90));
  const double t92 = ((t48) * (t67) + (t91));
  const double t18 = (t9 * -0.316);
  const double t54 = (t35 - t18);
  const double t17 = (t7 * -0.316);
  const double t53 = (t33 - t17);
  const double t71 = (t29 * t53);
  const double t72 = (-(t71));
  const double t73 = ((t26) * (t54) + (t72));
  const double t68 = (t36 - t23);
  const double t74 = (r3 * t54);
  const double t75 = (-(t74));
  const double t76 = ((t29) * (t68) + (t75));
  const double t69 = (t26 * t68);
  const double t70 = (-(t69));
  const double t77 = ((r3) * (t53) + (t70));
  const double t93 = (t43 * t77);
  const double t94 = ((r15) * (t76) + (t93));
  const double t95 = ((t48) * (t73) + (t94));
  const double t79 = (t35 - t35);
  const double t83 = (t33 - t33);
  const double t87 = (t46 * t83);
  const double t88 = (-(t87));
  const double t89 = ((t41) * (t79) + (t88));
  const double t78 = (t36 - t36);
  const double t80 = (t51 * t79);
  const double t81 = (-(t80));
  const double t82 = ((t46) * (t78) + (t81));
  const double t84 = (t41 * t78);
  const double t85 = (-(t84));
  const double t86 = ((t51) * (t83) + (t85));
  const double t96 = (t43 * t86);
  const double t97 = ((r15) * (t82) + (t96));
  const double t98 = ((t48) * (t89) + (t97));
  const double t61 = (t45 * t33);
  const double t62 = ((t40) * (t58) + (t61));
  const double t99 = (t45 * t57);
  const double t100 = ((t40) * (t55) + (t99));
  const double t101 = ((t50) * (t67) + (t100));
  const double t102 = (t45 * t77);
  const double t103 = ((t40) * (t76) + (t102));
  const double t104 = ((t50) * (t73) + (t103));
  const double t105 = (t45 * t86);
  const double t106 = ((t40) * (t82) + (t105));
  const double t107 = ((t50) * (t89) + (t106));
  const double t63 = (t46 * t33);
  const double t64 = ((t41) * (t58) + (t63));
  const double t108 = (t46 * t57);
  const double t109 = ((t41) * (t55) + (t108));
  const double t110 = ((t51) * (t67) + (t109));
  const double t111 = (t46 * t77);
  const double t112 = ((t41) * (t76) + (t111));
  const double t113 = ((t51) * (t73) + (t112));
  const double t114 = (t46 * t86);
  const double t115 = ((t41) * (t82) + (t114));
  const double t116 = ((t51) * (t89) + (t115));
  const double t117 = (t43 * r0);
  const double t118 = ((r15) * (r2) + (t117));
  const double t119 = (t43 * t29);
  const double t120 = ((r15) * (t26) + (t119));
  const double t121 = ((t48) * (r3) + (t120));
  const double t122 = (t43 * t46);
  const double t123 = ((r15) * (t41) + (t122));
  const double t124 = ((t48) * (t51) + (t123));
  const double t125 = (t45 * r0);
  const double t126 = ((t40) * (r2) + (t125));
  const double t127 = (t45 * t29);
  const double t128 = ((t40) * (t26) + (t127));
  const double t129 = ((t50) * (r3) + (t128));
  const double t130 = (t45 * t46);
  const double t131 = ((t40) * (t41) + (t130));
  const double t132 = ((t50) * (t51) + (t131));
  const double t133 = (t46 * r0);
  const double t134 = ((t41) * (r2) + (t133));
  const double t135 = (t46 * t29);
  const double t136 = ((t41) * (t26) + (t135));
  const double t137 = ((t51) * (r3) + (t136));
  const double t138 = (t46 * t46);
  const double t139 = ((t41) * (t41) + (t138));
  const double t140 = ((t51) * (t51) + (t139));
  J[0 * 7 + 0] = t60;
  J[0 * 7 + 1] = t92;
  J[0 * 7 + 2] = t95;
  J[0 * 7 + 3] = t98;
  J[1 * 7 + 0] = t62;
  J[1 * 7 + 1] = t101;
  J[1 * 7 + 2] = t104;
  J[1 * 7 + 3] = t107;
  J[2 * 7 + 0] = t64;
  J[2 * 7 + 1] = t110;
  J[2 * 7 + 2] = t113;
  J[2 * 7 + 3] = t116;
  J[3 * 7 + 0] = t48;
  J[3 * 7 + 1] = t118;
  J[3 * 7 + 2] = t121;
  J[3 * 7 + 3] = t124;
  J[4 * 7 + 0] = t50;
  J[4 * 7 + 1] = t126;
  J[4 * 7 + 2] = t129;
  J[4 * 7 + 3] = t132;
  J[5 * 7 + 0] = t51;
  J[5 * 7 + 1] = t134;
  J[5 * 7 + 2] = t137;
  J[5 * 7 + 3] = t140;
  }
}
#ifdef __cplusplus
}
#endif

