// Generated by fastfk for robot: skew_axis
// Task: spatial:link2[0]; spatial:link2[1]; spatial:link2[2]; spatial:link2[3]; spatial:link2[4]; spatial:link2[5]
#include "fk_jacobian.hpp"

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: link2
  {
  double fk_s15 = 0, fk_c14 = 0;
  fastfk_fast_sincos(q[0], &fk_s15, &fk_c14);
  const double r0 = fk_c14;
  const double r4 = (-0.70710678118654746 * fk_s15);
  const double t95 = (r4 * 0.14999999999999999);
  const double r2 = ((1 - r0) * 0.49999999999999989);
  const double t96 = (r0 * 0.14999999999999999);
  const double r3 = (0.70710678118654746 * fk_s15);
  double fk_s26 = 0, fk_c25 = 0;
  fastfk_fast_sincos(q[1], &fk_s26, &fk_c25);
  const double t91 = fk_s26;
  const double t98 = ((r3) * (0.14999999999999999) + (0.20000000000000001));
  const double r6 = (-0.70710678118654746 * t91);
  const double r8 = ((1 - fk_c25) * 0.49999999999999989);
  const double r11 = (((1 - fk_c25)) * (0.49999999999999989) + (fk_c25));
  const double t107 = ((r0) * (r8) + (((r4) * (r6) + ((r3 * r11)))));
  const double r7 = (0.70710678118654746 * t91);
  const double t108 = ((r0) * (r11) + (((r4) * (r7) + ((r3 * r8)))));
  const double r9 = (((1 - r0)) * (0.49999999999999989) + (r0));
  const double t105 = ((r4) * (r11) + (((r2) * (r7) + ((r9 * r8)))));
  const double r10 = ((r3) * (r6) + (((r9) * (fk_c25) + ((r2 * r7)))));
  const double r12 = ((r3) * (r8) + (((r9) * (r6) + ((r2 * r11)))));
  const double r13 = ((r3) * (r11) + (((r9) * (r7) + ((r2 * r8)))));
  const double r14 = ((r4) * (r6) + (((r2) * (fk_c25) + ((r9 * r7)))));
  const double r15 = ((r4) * (r8) + (((r2) * (r6) + ((r9 * r11)))));
  const double t106 = ((r0) * (r6) + (((r4) * (fk_c25) + ((r3 * r7)))));
  R[0] = r10;
  R[1] = r12;
  R[2] = r13;
  R[3] = r14;
  R[4] = r15;
  R[5] = t105;
  R[6] = t106;
  R[7] = t107;
  R[8] = t108;
  p[0] = t98;
  p[1] = t95;
  p[2] = t96;
  // Jacobian (6 x 2)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  const double t111 = ((0.70710678118654746) * (t95) + ((-((0.70710678118654746 * (t98 - 0.20000000000000001))))));
  const double t109 = (0.70710678118654746 * t96);
  const double t110 = (0 - t109);
  const double t117 = ((r2) * (0.70710678118654746) + ((r3 * 0.70710678118654746)));
  const double t115 = ((r4) * (0.14999999999999999) + ((-(t95))));
  const double t112 = ((r9) * (0.70710678118654746) + ((r4 * 0.70710678118654746)));
  const double t119 = ((t117) * (t115) + ((-((t112 * (t98 - t98))))));
  const double t113 = ((r0) * (0.14999999999999999) + ((-(t96))));
  const double t114 = ((r3) * (0.70710678118654746) + ((r0 * 0.70710678118654746)));
  const double t116 = ((t112) * (t113) + ((-((t114 * t115)))));
  const double t118 = ((t114) * ((t98 - t98)) + ((-((t117 * t113)))));
  J[0 * 2 + 0] = ((t106) * (t111) + (((r10) * (t109) + ((r14 * t110)))));
  J[0 * 2 + 1] = ((t106) * (t119) + (((r10) * (t116) + ((r14 * t118)))));
  J[1 * 2 + 0] = ((t107) * (t111) + (((r12) * (t109) + ((r15 * t110)))));
  J[1 * 2 + 1] = ((t107) * (t119) + (((r12) * (t116) + ((r15 * t118)))));
  J[2 * 2 + 0] = ((t108) * (t111) + (((r13) * (t109) + ((t105 * t110)))));
  J[2 * 2 + 1] = ((t108) * (t119) + (((r13) * (t116) + ((t105 * t118)))));
  J[3 * 2 + 0] = ((r10) * (0.70710678118654746) + ((r14 * 0.70710678118654746)));
  J[3 * 2 + 1] = ((t106) * (t114) + (((r10) * (t117) + ((r14 * t112)))));
  J[4 * 2 + 0] = ((r12) * (0.70710678118654746) + ((r15 * 0.70710678118654746)));
  J[4 * 2 + 1] = ((t107) * (t114) + (((r12) * (t117) + ((r15 * t112)))));
  J[5 * 2 + 0] = ((r13) * (0.70710678118654746) + ((t105 * 0.70710678118654746)));
  J[5 * 2 + 1] = ((t108) * (t114) + (((r13) * (t117) + ((t105 * t112)))));
  }
}
#ifdef __cplusplus
}
#endif

