// Generated by fastfk for robot: chain12
// Task: spatial:link6[0]; spatial:link6[1]; spatial:link6[2]; spatial:link6[3]; spatial:link6[4]; spatial:link6[5]
#include "fk_jacobian.hpp"

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: link6
  {
  double fk_s57 = 0, fk_c56 = 0;
  fastfk_fast_sincos(q[0], &fk_s57, &fk_c56);
  const double r0 = fk_c56;
  double fk_s61 = 0, fk_c60 = 0;
  fastfk_fast_sincos(q[1], &fk_s61, &fk_c60);
  const double r3 = fk_c60;
  const double r5 = (r0 * r3);
  const double t172 = ((r5) * (0.14000000000000001) + (((r0) * (0.13) + (0.12))));
  const double t156 = (fk_s57 * r3);
  const double t173 = ((fk_s57) * (0.13) + ((t156 * 0.14000000000000001)));
  const double t153 = (-(fk_s61));
  double fk_s72 = 0, fk_c71 = 0;
  fastfk_fast_sincos(q[2], &fk_s72, &fk_c71);
  const double r7 = fk_c71;
  const double t161 = (t153 * r7);
  const double t178 = ((t153) * (0.14000000000000001) + ((t161 * 0.14999999999999999)));
  const double r2 = (-(fk_s57));
  const double t174 = ((r5) * (r7) + ((r2 * fk_s72)));
  double fk_s95 = 0, fk_c94 = 0;
  fastfk_fast_sincos(q[3], &fk_s95, &fk_c94);
  const double r10 = fk_c94;
  const double r6 = (r0 * fk_s61);
  const double r12 = (-(fk_s95));
  const double t179 = ((t174) * (r10) + ((r6 * r12)));
  const double t185 = ((t179) * (0.12) + (((t174) * (0.14999999999999999) + (t172))));
  const double t176 = ((t156) * (r7) + ((r0 * fk_s72)));
  const double t157 = (fk_s57 * fk_s61);
  const double t181 = ((t176) * (r10) + ((t157 * r12)));
  const double t186 = ((t181) * (0.12) + (((t176) * (0.14999999999999999) + (t173))));
  const double t183 = ((t161) * (r10) + ((r3 * r12)));
  double fk_s122 = 0, fk_c121 = 0;
  fastfk_fast_sincos(q[4], &fk_s122, &fk_c121);
  const double r13 = fk_c121;
  const double r9 = (-(fk_s72));
  const double t162 = (t153 * r9);
  const double t191 = ((t183) * (r13) + ((t162 * fk_s122)));
  const double t195 = ((t191) * (0.13) + (((t183) * (0.12) + (t178))));
  const double t177 = ((t156) * (r9) + ((r0 * r7)));
  const double t189 = ((t181) * (r13) + ((t177 * fk_s122)));
  const double t194 = ((t189) * (0.13) + (t186));
  const double t175 = ((r5) * (r9) + ((r2 * r7)));
  const double t182 = ((t176) * (fk_s95) + ((t157 * r10)));
  const double t184 = ((t161) * (fk_s95) + ((r3 * r10)));
  const double t187 = ((t179) * (r13) + ((t175 * fk_s122)));
  const double t193 = ((t187) * (0.13) + (t185));
  const double t180 = ((t174) * (fk_s95) + ((r6 * r10)));
  const double r15 = (-(fk_s122));
  const double t192 = ((t183) * (r15) + ((t162 * r13)));
  double fk_s149 = 0, fk_c148 = 0;
  fastfk_fast_sincos(q[5], &fk_s149, &fk_c148);
  const double t169 = fk_c148;
  const double t171 = (-(fk_s149));
  const double t200 = ((t191) * (t169) + ((t184 * t171)));
  const double t201 = ((t191) * (fk_s149) + ((t184 * t169)));
  const double t190 = ((t181) * (r15) + ((t177 * r13)));
  const double t188 = ((t179) * (r15) + ((t175 * r13)));
  const double t196 = ((t187) * (t169) + ((t180 * t171)));
  const double t197 = ((t187) * (fk_s149) + ((t180 * t169)));
  const double t198 = ((t189) * (t169) + ((t182 * t171)));
  const double t199 = ((t189) * (fk_s149) + ((t182 * t169)));
  R[0] = t196;
  R[1] = t188;
  R[2] = t197;
  R[3] = t198;
  R[4] = t190;
  R[5] = t199;
  R[6] = t200;
  R[7] = t192;
  R[8] = t201;
  p[0] = t193;
  p[1] = t194;
  p[2] = t195;
  // Jacobian (6 x 12)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  const double t204 = (0 - t194);
  const double t202 = (t193 - 0.12);
  const double t207 = ((r2) * ((t194 - (fk_s57 * 0.13))) + ((-((r0 * (t193 - ((r0) * (0.13) + (0.12))))))));
  const double t205 = (r0 * t195);
  const double t206 = (0 - (r2 * t195));
  const double t210 = ((r6) * ((t194 - t173)) + ((-((t157 * (t193 - t172))))));
  const double t203 = (t195 - (t153 * 0.14000000000000001));
  const double t208 = ((t157) * (t203) + ((-((r3 * (t194 - t173))))));
  const double t209 = ((r3) * ((t193 - t172)) + ((-((r6 * t203)))));
  const double t211 = (t194 - ((t176) * (0.14999999999999999) + (t173)));
  const double t213 = (t193 - ((t174) * (0.14999999999999999) + (t172)));
  const double t215 = ((t175) * (t211) + ((-((t177 * t213)))));
  const double t212 = ((t177) * ((t195 - t178)) + ((-((t162 * t211)))));
  const double t214 = ((t162) * (t213) + ((-((t175 * (t195 - t178))))));
  const double t219 = ((t180) * ((t194 - t186)) + ((-((t182 * (t193 - t185))))));
  const double t216 = (t195 - ((t183) * (0.12) + (t178)));
  const double t217 = ((t182) * (t216) + ((-((t184 * (t194 - t186))))));
  const double t218 = ((t184) * ((t193 - t185)) + ((-((t180 * t216)))));
  const double t222 = ((t188) * ((t194 - t194)) + ((-((t190 * (t193 - t193))))));
  const double t220 = ((t190) * ((t195 - t195)) + ((-((t192 * (t194 - t194))))));
  const double t221 = ((t192) * ((t193 - t193)) + ((-((t188 * (t195 - t195))))));
  J[0 * 12 + 0] = ((t196) * (t204) + ((t198 * t202)));
  J[0 * 12 + 1] = ((t200) * (t207) + (((t196) * (t205) + ((t198 * t206)))));
  J[0 * 12 + 2] = ((t200) * (t210) + (((t196) * (t208) + ((t198 * t209)))));
  J[0 * 12 + 3] = ((t200) * (t215) + (((t196) * (t212) + ((t198 * t214)))));
  J[0 * 12 + 4] = ((t200) * (t219) + (((t196) * (t217) + ((t198 * t218)))));
  J[0 * 12 + 5] = ((t200) * (t222) + (((t196) * (t220) + ((t198 * t221)))));
  J[1 * 12 + 0] = ((t188) * (t204) + ((t190 * t202)));
  J[1 * 12 + 1] = ((t192) * (t207) + (((t188) * (t205) + ((t190 * t206)))));
  J[1 * 12 + 2] = ((t192) * (t210) + (((t188) * (t208) + ((t190 * t209)))));
  J[1 * 12 + 3] = ((t192) * (t215) + (((t188) * (t212) + ((t190 * t214)))));
  J[1 * 12 + 4] = ((t192) * (t219) + (((t188) * (t217) + ((t190 * t218)))));
  J[1 * 12 + 5] = ((t192) * (t222) + (((t188) * (t220) + ((t190 * t221)))));
  J[2 * 12 + 0] = ((t197) * (t204) + ((t199 * t202)));
  J[2 * 12 + 1] = ((t201) * (t207) + (((t197) * (t205) + ((t199 * t206)))));
  J[2 * 12 + 2] = ((t201) * (t210) + (((t197) * (t208) + ((t199 * t209)))));
  J[2 * 12 + 3] = ((t201) * (t215) + (((t197) * (t212) + ((t199 * t214)))));
  J[2 * 12 + 4] = ((t201) * (t219) + (((t197) * (t217) + ((t199 * t218)))));
  J[2 * 12 + 5] = ((t201) * (t222) + (((t197) * (t220) + ((t199 * t221)))));
  J[3 * 12 + 0] = t200;
  J[3 * 12 + 1] = ((t196) * (r2) + ((t198 * r0)));
  J[3 * 12 + 2] = ((t200) * (r3) + (((t196) * (r6) + ((t198 * t157)))));
  J[3 * 12 + 3] = ((t200) * (t162) + (((t196) * (t175) + ((t198 * t177)))));
  J[3 * 12 + 4] = ((t200) * (t184) + (((t196) * (t180) + ((t198 * t182)))));
  J[3 * 12 + 5] = ((t200) * (t192) + (((t196) * (t188) + ((t198 * t190)))));
  J[4 * 12 + 0] = t192;
  J[4 * 12 + 1] = ((t188) * (r2) + ((t190 * r0)));
  J[4 * 12 + 2] = ((t192) * (r3) + (((t188) * (r6) + ((t190 * t157)))));
  J[4 * 12 + 3] = ((t192) * (t162) + (((t188) * (t175) + ((t190 * t177)))));
  J[4 * 12 + 4] = ((t192) * (t184) + (((t188) * (t180) + ((t190 * t182)))));
  J[4 * 12 + 5] = ((t192) * (t192) + (((t188) * (t188) + ((t190 * t190)))));
  J[5 * 12 + 0] = t201;
  J[5 * 12 + 1] = ((t197) * (r2) + ((t199 * r0)));
  J[5 * 12 + 2] = ((t201) * (r3) + (((t197) * (r6) + ((t199 * t157)))));
  J[5 * 12 + 3] = ((t201) * (t162) + (((t197) * (t175) + ((t199 * t177)))));
  J[5 * 12 + 4] = ((t201) * (t184) + (((t197) * (t180) + ((t199 * t182)))));
  J[5 * 12 + 5] = ((t201) * (t192) + (((t197) * (t188) + ((t199 * t190)))));
  }
}
#ifdef __cplusplus
}
#endif

