// Generated by fastfk for robot: ur3e_robot
// Task: spatial:forearm_link[0]; spatial:forearm_link[1]; spatial:forearm_link[2]; spatial:forearm_link[3]; spatial:forearm_link[4]; spatial:forearm_link[5]
#include "fk_jacobian.hpp"

// q-invariant R/p (call once; not written by fastfk_task).
void fastfk_init_static_frames(double* R, double* p) {
  // forearm_link
  R[8] = 0.0;
}

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: forearm_link
  {
  double fk_s42 = 0, fk_c41 = 0;
  fastfk_fast_sincos(q[0], &fk_s42, &fk_c41);
  const double r0 = fk_c41;
  const double t60 = (-(fk_s42));
  double fk_s48 = 0, fk_c47 = 0;
  fastfk_fast_sincos(q[1], &fk_s48, &fk_c47);
  const double r2 = fk_s48;
  const double t67 = ((-(r0)) * (-(r2)));
  const double r6 = ((-(r0)) * fk_c47);
  const double t70 = (r6 * -0.24354999999999999);
  const double r7 = (t60 * fk_c47);
  const double t71 = (r7 * -0.24354999999999999);
  double fk_s58 = 0, fk_c57 = 0;
  fastfk_fast_sincos(q[2], &fk_s58, &fk_c57);
  const double r3 = fk_c57;
  const double t72 = ((r2) * (-0.24354999999999999) + (0.15185000000000001));
  const double t77 = ((r2) * (r3) + ((fk_c47 * fk_s58)));
  const double r5 = (-(fk_s58));
  const double r8 = (t60 * (-(r2)));
  const double t76 = ((r7) * (r5) + ((r8 * r3)));
  const double r9 = ((r6) * (r3) + ((t67 * fk_s58)));
  const double r10 = ((r6) * (r5) + ((t67 * r3)));
  const double r11 = ((r7) * (r3) + ((r8 * fk_s58)));
  const double r12 = ((r2) * (r5) + ((fk_c47 * r3)));
  R[0] = r9;
  R[1] = r10;
  R[2] = t60;
  R[3] = r11;
  R[4] = t76;
  R[5] = r0;
  R[6] = t77;
  R[7] = r12;
  p[0] = t70;
  p[1] = t71;
  p[2] = t72;
  // Jacobian (6 x 6)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  const double t79 = (0 - t71);
  const double t80 = ((t60) * (t71) + ((-((r0 * t70)))));
  const double t81 = (r0 * (t72 - 0.15185000000000001));
  const double t82 = (0 - (t60 * (t72 - 0.15185000000000001)));
  const double t83 = ((t60) * (((r7) * (-0.24354999999999999) + ((-(t71))))) + ((-((r0 * ((r6) * (-0.24354999999999999) + ((-(t70)))))))));
  const double t84 = (r0 * (t72 - t72));
  const double t85 = (0 - (t60 * (t72 - t72)));
  const double t86 = ((r9) * (t60) + ((r11 * r0)));
  const double t87 = ((r10) * (t60) + ((t76 * r0)));
  const double t88 = ((t60) * (t60) + ((r0 * r0)));
  J[0 * 6 + 0] = ((r9) * (t79) + ((r11 * t70)));
  J[0 * 6 + 1] = ((t77) * (t80) + (((r9) * (t81) + ((r11 * t82)))));
  J[0 * 6 + 2] = ((t77) * (t83) + (((r9) * (t84) + ((r11 * t85)))));
  J[1 * 6 + 0] = ((r10) * (t79) + ((t76 * t70)));
  J[1 * 6 + 1] = ((r12) * (t80) + (((r10) * (t81) + ((t76 * t82)))));
  J[1 * 6 + 2] = ((r12) * (t83) + (((r10) * (t84) + ((t76 * t85)))));
  J[2 * 6 + 0] = ((t60) * (t79) + ((r0 * t70)));
  J[2 * 6 + 1] = ((t60) * (t81) + ((r0 * t82)));
  J[2 * 6 + 2] = ((t60) * (t84) + ((r0 * t85)));
  J[3 * 6 + 0] = t77;
  J[3 * 6 + 1] = t86;
  J[3 * 6 + 2] = t86;
  J[4 * 6 + 0] = r12;
  J[4 * 6 + 1] = t87;
  J[4 * 6 + 2] = t87;
  J[5 * 6 + 1] = t88;
  J[5 * 6 + 2] = t88;
  }
}
#ifdef __cplusplus
}
#endif

