// Generated by fastfk for robot: panda_arm
// Task: spatial:panda_link5[0]; spatial:panda_link5[1]; spatial:panda_link5[2]; spatial:panda_link5[3]; spatial:panda_link5[4]; spatial:panda_link5[5]
#include "fk_jacobian.hpp"

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: panda_link5
  {
  double fk_s40 = 0, fk_c39 = 0;
  fastfk_fast_sincos(q[0], &fk_s40, &fk_c39);
  const double r0 = fk_c39;
  double fk_s44 = 0, fk_c43 = 0;
  fastfk_fast_sincos(q[1], &fk_s44, &fk_c43);
  const double r3 = fk_c43;
  const double t142 = (((-(r3))) * (-0.316) + (0.33300000000000002));
  const double r4 = (-(fk_s44));
  const double r5 = (r0 * r4);
  double fk_s54 = 0, fk_c53 = 0;
  fastfk_fast_sincos(q[2], &fk_s54, &fk_c53);
  const double r6 = fk_c53;
  const double r2 = (-(fk_s40));
  const double r14 = (((r0 * r3)) * (r6) + ((r2 * fk_s54)));
  const double t148 = ((r5) * (-0.316) + ((r14 * 0.082500000000000004)));
  const double t133 = (fk_s40 * r4);
  const double t145 = (((fk_s40 * r3)) * (r6) + ((r0 * fk_s54)));
  const double t149 = ((t133) * (-0.316) + ((t145 * 0.082500000000000004)));
  const double r8 = (-(fk_s54));
  const double t155 = (-((((fk_s40 * r3)) * (r8) + ((r0 * r6)))));
  const double t158 = (-((r4 * r8)));
  const double t147 = (r4 * r6);
  double fk_s79 = 0, fk_c78 = 0;
  fastfk_fast_sincos(q[3], &fk_s79, &fk_c78);
  const double r9 = fk_c78;
  const double t156 = ((t147) * (r9) + ((r3 * fk_s79)));
  const double r11 = (-(fk_s79));
  const double t157 = ((t147) * (r11) + ((r3 * r9)));
  const double t161 = (((t147) * (0.082500000000000004) + (t142)) + ((t156) * (-0.082500000000000004) + ((t157 * 0.38400000000000001))));
  const double t146 = (-(t133));
  const double t152 = (-((((r0 * r3)) * (r8) + ((r2 * r6)))));
  const double t153 = ((t145) * (r9) + ((t146 * fk_s79)));
  const double t154 = ((t145) * (r11) + ((t146 * r9)));
  const double t160 = (t149 + ((t153) * (-0.082500000000000004) + ((t154 * 0.38400000000000001))));
  const double r15 = (-(r5));
  const double t150 = ((r14) * (r9) + ((r15 * fk_s79)));
  const double t151 = ((r14) * (r11) + ((r15 * r9)));
  const double t159 = (t148 + ((t150) * (-0.082500000000000004) + ((t151 * 0.38400000000000001))));
  double fk_s111 = 0, fk_c110 = 0;
  fastfk_fast_sincos(q[4], &fk_s111, &fk_c110);
  const double r12 = fk_c110;
  const double r13 = (-(fk_s111));
  const double t167 = ((t156) * (r12) + ((t158 * r13)));
  const double t163 = (-(r12));
  const double t168 = ((t156) * (r13) + ((t158 * t163)));
  const double t162 = ((t150) * (r12) + ((t152 * r13)));
  const double t164 = ((t150) * (r13) + ((t152 * t163)));
  const double t165 = ((t153) * (r12) + ((t155 * r13)));
  const double t166 = ((t153) * (r13) + ((t155 * t163)));
  R[0] = t162;
  R[1] = t164;
  R[2] = t151;
  R[3] = t165;
  R[4] = t166;
  R[5] = t154;
  R[6] = t167;
  R[7] = t168;
  R[8] = t157;
  p[0] = t159;
  p[1] = t160;
  p[2] = t161;
  // Jacobian (6 x 7)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  const double t173 = (0 - t160);
  const double t174 = ((r2) * (t160) + ((-((r0 * t159)))));
  const double t169 = (r0 * (t161 - 0.33300000000000002));
  const double t170 = (0 - (r2 * (t161 - 0.33300000000000002)));
  const double t172 = (t160 - (t133 * -0.316));
  const double t171 = (t159 - (r5 * -0.316));
  const double t175 = ((r15) * (t172) + ((-((t146 * t171)))));
  const double t176 = ((t146) * ((t161 - t142)) + ((-((r3 * t172)))));
  const double t177 = ((r3) * (t171) + ((-((r15 * (t161 - t142))))));
  const double t181 = ((t152) * ((t160 - t149)) + ((-((t155 * (t159 - t148))))));
  const double t178 = (t161 - ((t147) * (0.082500000000000004) + (t142)));
  const double t179 = ((t155) * (t178) + ((-((t158 * (t160 - t149))))));
  const double t180 = ((t158) * ((t159 - t148)) + ((-((t152 * t178)))));
  const double t182 = ((t151) * ((t160 - t160)) + ((-((t154 * (t159 - t159))))));
  const double t183 = ((t154) * ((t161 - t161)) + ((-((t157 * (t160 - t160))))));
  const double t184 = ((t157) * ((t159 - t159)) + ((-((t151 * (t161 - t161))))));
  J[0 * 7 + 0] = ((t162) * (t173) + ((t165 * t159)));
  J[0 * 7 + 1] = ((t167) * (t174) + (((t162) * (t169) + ((t165 * t170)))));
  J[0 * 7 + 2] = ((t167) * (t175) + (((t162) * (t176) + ((t165 * t177)))));
  J[0 * 7 + 3] = ((t167) * (t181) + (((t162) * (t179) + ((t165 * t180)))));
  J[0 * 7 + 4] = ((t167) * (t182) + (((t162) * (t183) + ((t165 * t184)))));
  J[1 * 7 + 0] = ((t164) * (t173) + ((t166 * t159)));
  J[1 * 7 + 1] = ((t168) * (t174) + (((t164) * (t169) + ((t166 * t170)))));
  J[1 * 7 + 2] = ((t168) * (t175) + (((t164) * (t176) + ((t166 * t177)))));
  J[1 * 7 + 3] = ((t168) * (t181) + (((t164) * (t179) + ((t166 * t180)))));
  J[1 * 7 + 4] = ((t168) * (t182) + (((t164) * (t183) + ((t166 * t184)))));
  J[2 * 7 + 0] = ((t151) * (t173) + ((t154 * t159)));
  J[2 * 7 + 1] = ((t157) * (t174) + (((t151) * (t169) + ((t154 * t170)))));
  J[2 * 7 + 2] = ((t157) * (t175) + (((t151) * (t176) + ((t154 * t177)))));
  J[2 * 7 + 3] = ((t157) * (t181) + (((t151) * (t179) + ((t154 * t180)))));
  J[2 * 7 + 4] = ((t157) * (t182) + (((t151) * (t183) + ((t154 * t184)))));
  J[3 * 7 + 0] = t167;
  J[3 * 7 + 1] = ((t162) * (r2) + ((t165 * r0)));
  J[3 * 7 + 2] = ((t167) * (r3) + (((t162) * (r15) + ((t165 * t146)))));
  J[3 * 7 + 3] = ((t167) * (t158) + (((t162) * (t152) + ((t165 * t155)))));
  J[3 * 7 + 4] = ((t167) * (t157) + (((t162) * (t151) + ((t165 * t154)))));
  J[4 * 7 + 0] = t168;
  J[4 * 7 + 1] = ((t164) * (r2) + ((t166 * r0)));
  J[4 * 7 + 2] = ((t168) * (r3) + (((t164) * (r15) + ((t166 * t146)))));
  J[4 * 7 + 3] = ((t168) * (t158) + (((t164) * (t152) + ((t166 * t155)))));
  J[4 * 7 + 4] = ((t168) * (t157) + (((t164) * (t151) + ((t166 * t154)))));
  J[5 * 7 + 0] = t157;
  J[5 * 7 + 1] = ((t151) * (r2) + ((t154 * r0)));
  J[5 * 7 + 2] = ((t157) * (r3) + (((t151) * (r15) + ((t154 * t146)))));
  J[5 * 7 + 3] = ((t157) * (t158) + (((t151) * (t152) + ((t154 * t155)))));
  J[5 * 7 + 4] = ((t157) * (t157) + (((t151) * (t151) + ((t154 * t154)))));
  }
}
#ifdef __cplusplus
}
#endif

