// Generated by fastfk for robot: six_dof
// Task: spatial:link3[0]; spatial:link3[1]; spatial:link3[2]; spatial:link3[3]; spatial:link3[4]; spatial:link3[5]
#include "fk_jacobian.hpp"

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: link3
  {
  double fk_s33 = 0, fk_c32 = 0;
  fastfk_fast_sincos(q[0], &fk_s33, &fk_c32);
  const double r0 = fk_c32;
  double fk_s37 = 0, fk_c36 = 0;
  fastfk_fast_sincos(q[1], &fk_s37, &fk_c36);
  const double r3 = fk_c36;
  const double r6 = (fk_s33 * r3);
  const double t22 = (r6 * 0.14999999999999999);
  const double t5 = (-(fk_s37));
  const double t23 = (t5 * 0.14999999999999999);
  const double r2 = (-(fk_s33));
  double fk_s46 = 0, fk_c45 = 0;
  fastfk_fast_sincos(q[2], &fk_s46, &fk_c45);
  const double r8 = fk_c45;
  const double t19 = (t5 * r8);
  const double t17 = (r0 * fk_s46);
  const double t18 = (r0 * r8);
  const double r4 = (r0 * r3);
  const double t21 = (r4 * 0.14999999999999999);
  const double t24 = ((r0) * (0.14999999999999999) + (t21));
  const double r5 = (r0 * fk_s37);
  const double t15 = (r2 * fk_s46);
  const double t16 = (r2 * r8);
  const double t25 = ((fk_s33) * (0.14999999999999999) + (t22));
  const double r7 = (fk_s33 * fk_s37);
  const double r9 = (-(fk_s46));
  const double t20 = (t5 * r9);
  const double r10 = ((r4) * (r8) + (t15));
  const double r11 = ((r4) * (r9) + (t16));
  const double r12 = ((r6) * (r8) + (t17));
  const double r13 = ((r6) * (r9) + (t18));
  R[0] = r10;
  R[1] = r11;
  R[2] = r5;
  R[3] = r12;
  R[4] = r13;
  R[5] = r7;
  R[6] = t19;
  R[7] = t20;
  R[8] = r3;
  p[0] = t24;
  p[1] = t25;
  p[2] = t23;
  // Jacobian (6 x 6)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  const double t33 = (0 - t25);
  const double t34 = (r12 * t24);
  const double t35 = ((r10) * (t33) + (t34));
  const double t11 = (fk_s33 * 0.14999999999999999);
  const double t31 = (t25 - t11);
  const double t10 = (r0 * 0.14999999999999999);
  const double t30 = (t24 - t10);
  const double t32 = (r0 * t30);
  const double t43 = (-(t32));
  const double t44 = ((r2) * (t31) + (t43));
  const double t40 = (r0 * t23);
  const double t41 = (r2 * t23);
  const double t42 = (0 - t41);
  const double t58 = (r12 * t42);
  const double t59 = ((r10) * (t40) + (t58));
  const double t60 = ((t19) * (t44) + (t59));
  const double t47 = (t25 - t25);
  const double t51 = (t24 - t24);
  const double t55 = (r7 * t51);
  const double t56 = (-(t55));
  const double t57 = ((r5) * (t47) + (t56));
  const double t45 = (-(t23));
  const double t46 = ((t5) * (0.14999999999999999) + (t45));
  const double t48 = (r3 * t47);
  const double t49 = (-(t48));
  const double t50 = ((r7) * (t46) + (t49));
  const double t52 = (r5 * t46);
  const double t53 = (-(t52));
  const double t54 = ((r3) * (t51) + (t53));
  const double t61 = (r12 * t54);
  const double t62 = ((r10) * (t50) + (t61));
  const double t63 = ((t19) * (t57) + (t62));
  const double t36 = (r13 * t24);
  const double t37 = ((r11) * (t33) + (t36));
  const double t64 = (r13 * t42);
  const double t65 = ((r11) * (t40) + (t64));
  const double t66 = ((t20) * (t44) + (t65));
  const double t67 = (r13 * t54);
  const double t68 = ((r11) * (t50) + (t67));
  const double t69 = ((t20) * (t57) + (t68));
  const double t38 = (r7 * t24);
  const double t39 = ((r5) * (t33) + (t38));
  const double t70 = (r7 * t42);
  const double t71 = ((r5) * (t40) + (t70));
  const double t72 = ((r3) * (t44) + (t71));
  const double t73 = (r7 * t54);
  const double t74 = ((r5) * (t50) + (t73));
  const double t75 = ((r3) * (t57) + (t74));
  const double t76 = (r12 * r0);
  const double t77 = ((r10) * (r2) + (t76));
  const double t78 = (r12 * r7);
  const double t79 = ((r10) * (r5) + (t78));
  const double t80 = ((t19) * (r3) + (t79));
  const double t81 = (r13 * r0);
  const double t82 = ((r11) * (r2) + (t81));
  const double t83 = (r13 * r7);
  const double t84 = ((r11) * (r5) + (t83));
  const double t85 = ((t20) * (r3) + (t84));
  const double t86 = (r7 * r0);
  const double t87 = ((r5) * (r2) + (t86));
  const double t88 = (r7 * r7);
  const double t89 = ((r5) * (r5) + (t88));
  const double t90 = ((r3) * (r3) + (t89));
  J[0 * 6 + 0] = t35;
  J[0 * 6 + 1] = t60;
  J[0 * 6 + 2] = t63;
  J[1 * 6 + 0] = t37;
  J[1 * 6 + 1] = t66;
  J[1 * 6 + 2] = t69;
  J[2 * 6 + 0] = t39;
  J[2 * 6 + 1] = t72;
  J[2 * 6 + 2] = t75;
  J[3 * 6 + 0] = t19;
  J[3 * 6 + 1] = t77;
  J[3 * 6 + 2] = t80;
  J[4 * 6 + 0] = t20;
  J[4 * 6 + 1] = t82;
  J[4 * 6 + 2] = t85;
  J[5 * 6 + 0] = r3;
  J[5 * 6 + 1] = t87;
  J[5 * 6 + 2] = t90;
  }
}
#ifdef __cplusplus
}
#endif

