// Generated by fastfk for robot: panda
// Task: spatial:panda_link2[0]; spatial:panda_link2[1]; spatial:panda_link2[2]; spatial:panda_link2[3]; spatial:panda_link2[4]; spatial:panda_link2[5]
#include "fk_jacobian.hpp"

// q-invariant R/p (call once; not written by fastfk_task).
void fastfk_init_static_frames(double* R, double* p) {
  // panda_link2
  R[8] = 0.0;
  p[0] = 0.0;
  p[1] = 0.0;
  p[2] = 0.33300000000000002;
}

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: panda_link2
  {
  double fk_s58 = 0, fk_c57 = 0;
  fastfk_fast_sincos(q[0], &fk_s58, &fk_c57);
  const double r0 = fk_c57;
  const double r1 = (-(fk_s58));
  double fk_s61 = 0, fk_c60 = 0;
  fastfk_fast_sincos(q[1], &fk_s61, &fk_c60);
  const double r2 = fk_c60;
  const double r3 = (-(fk_s61));
  R[0] = (r0 * r2);
  R[1] = (r0 * r3);
  R[2] = r1;
  R[3] = (fk_s58 * r2);
  R[4] = (fk_s58 * r3);
  R[5] = r0;
  R[6] = r3;
  R[7] = (-(r2));
  // Jacobian (6 x 9)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  J[3 * 9 + 0] = r3;
  J[3 * 9 + 1] = (((r0 * r2)) * (r1) + (((fk_s58 * r2) * r0)));
  J[4 * 9 + 0] = (-(r2));
  J[4 * 9 + 1] = (((r0 * r3)) * (r1) + (((fk_s58 * r3) * r0)));
  J[5 * 9 + 1] = ((r1) * (r1) + ((r0 * r0)));
  }
}
#ifdef __cplusplus
}
#endif

