// Generated by fastfk for robot: panda_arm
// Task: spatial:panda_link1[0]; spatial:panda_link1[1]; spatial:panda_link1[2]; spatial:panda_link1[3]; spatial:panda_link1[4]; spatial:panda_link1[5]
#include "fk_jacobian.hpp"

// q-invariant R/p (call once; not written by fastfk_task).
void fastfk_init_static_frames(double* R, double* p) {
  // panda_link1
  R[2] = 0.0;
  R[5] = 0.0;
  R[6] = 0.0;
  R[7] = 0.0;
  R[8] = 1.0;
  p[0] = 0.0;
  p[1] = 0.0;
  p[2] = 0.33300000000000002;
}

// q-invariant Jacobian entries (call once; not written by fastfk_task).
void fastfk_init_static_jacobian(double* J) {
  J[5 * 7 + 0] = 1.0;
}

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: panda_link1
  {
  double fk_s40 = 0, fk_c39 = 0;
  fastfk_fast_sincos(q[0], &fk_s40, &fk_c39);
  const double r0 = fk_c39;
  R[0] = r0;
  R[1] = (-(fk_s40));
  R[3] = fk_s40;
  R[4] = r0;
  // Jacobian (6 x 7)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  }
}
#ifdef __cplusplus
}
#endif

