// Generated by fastfk for robot: ur3e_robot
// Task: spatial:shoulder_link[0]; spatial:shoulder_link[1]; spatial:shoulder_link[2]; spatial:shoulder_link[3]; spatial:shoulder_link[4]; spatial:shoulder_link[5]
#include "fk_jacobian.hpp"

// q-invariant R/p (call once; not written by fastfk_task).
void fastfk_init_static_frames(double* R, double* p) {
  // shoulder_link
  R[2] = 0.0;
  R[5] = 0.0;
  R[6] = 0.0;
  R[7] = 0.0;
  R[8] = 1.0;
  p[0] = 0.0;
  p[1] = 0.0;
  p[2] = 0.15185000000000001;
}

// q-invariant Jacobian entries (call once; not written by fastfk_task).
void fastfk_init_static_jacobian(double* J) {
  J[5 * 6 + 0] = 1.0;
}

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: shoulder_link
  {
  double fk_s42 = 0, fk_c41 = 0;
  fastfk_fast_sincos(q[0], &fk_s42, &fk_c41);
  const double r0 = fk_s42;
  const double r1 = (-(fk_c41));
  R[0] = r1;
  R[1] = r0;
  R[3] = (-(r0));
  R[4] = r1;
  // Jacobian (6 x 6)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  }
}
#ifdef __cplusplus
}
#endif

