// Generated by fastfk for robot: two_link
// Task: spatial:link2[0]; spatial:link2[1]; spatial:link2[2]; spatial:link2[3]; spatial:link2[4]; spatial:link2[5]
#include "fk_jacobian.hpp"

// q-invariant R/p (call once; not written by fastfk_task).
void fastfk_init_static_frames(double* R, double* p) {
  // link2
  R[7] = 0.0;
  p[2] = 0.0;
}

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: link2
  {
  double fk_s14 = 0, fk_c13 = 0;
  fastfk_fast_sincos(q[0], &fk_s14, &fk_c13);
  const double r0 = fk_c13;
  const double r2 = (-(fk_s14));
  double fk_s17 = 0, fk_c16 = 0;
  fastfk_fast_sincos(q[1], &fk_s17, &fk_c16);
  const double r3 = fk_c16;
  const double r5 = (r0 * r3);
  const double r6 = (r0 * fk_s17);
  R[0] = r5;
  R[1] = r2;
  R[2] = r6;
  R[3] = (fk_s14 * r3);
  R[4] = r0;
  R[5] = (fk_s14 * fk_s17);
  R[6] = (-(fk_s17));
  R[8] = r3;
  p[0] = r0;
  p[1] = fk_s14;
  // Jacobian (6 x 2)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  const double t31 = (0 - fk_s14);
  const double t29 = ((fk_s14 * r3) * r0);
  const double t32 = ((r2) * ((fk_s14 - fk_s14)) + ((-((r0 * (r0 - r0))))));
  const double t30 = ((fk_s14 * fk_s17) * r0);
  J[0 * 2 + 0] = ((r5) * (t31) + (t29));
  J[0 * 2 + 1] = ((-(fk_s17)) * t32);
  J[1 * 2 + 0] = ((r2) * (t31) + ((r0 * r0)));
  J[2 * 2 + 0] = ((r6) * (t31) + (t30));
  J[2 * 2 + 1] = (r3 * t32);
  J[3 * 2 + 0] = (-(fk_s17));
  J[3 * 2 + 1] = ((r5) * (r2) + (t29));
  J[4 * 2 + 1] = ((r2) * (r2) + ((r0 * r0)));
  J[5 * 2 + 0] = r3;
  J[5 * 2 + 1] = ((r6) * (r2) + (t30));
  }
}
#ifdef __cplusplus
}
#endif

