#pragma once
// Generated by fastfk for robot: chain12
// Task: spatial:link2[0]; spatial:link2[1]; spatial:link2[2]; spatial:link2[3]; spatial:link2[4]; spatial:link2[5]
// FASTFK_TASK_ABI: spatial_local
// FASTFK_CODEGEN: sincos,fast-trig,no-fma,min-regs,budget=16,share=cost-aware
// FASTFK_CXX_FLAGS: -O2 -std=c++17 -march=native -ffp-contract=off
#include <cmath>
#include "fk_fast_math.hpp"
#ifdef __cplusplus
extern "C" {
#endif
void fastfk_init_static_frames(double* R /*[9]*/, double* p /*[3]*/);

void fastfk_task(
    const double* q,
    double* R /*[9]*/,
    double* p /*[3]*/,
    double* J /*[6 x 12] row-major*/);
#ifdef __cplusplus
}
#endif
