// Generated by fastfk for robot: chain12
// Task: spatial:link2[0]; spatial:link2[1]; spatial:link2[2]; spatial:link2[3]; spatial:link2[4]; spatial:link2[5]
#include "fk_jacobian.hpp"

// q-invariant R/p (call once; not written by fastfk_task).
void fastfk_init_static_frames(double* R, double* p) {
  // link2
  R[7] = 0.0;
  p[2] = 0.0;
}

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: link2
  {
  double fk_s57 = 0, fk_c56 = 0;
  fastfk_fast_sincos(q[0], &fk_s57, &fk_c56);
  const double r0 = fk_c56;
  const double t35 = (fk_s57 * 0.13);
  const double r2 = (-(fk_s57));
  double fk_s61 = 0, fk_c60 = 0;
  fastfk_fast_sincos(q[1], &fk_s61, &fk_c60);
  const double r3 = fk_c60;
  const double t34 = (fk_s57 * fk_s61);
  const double t36 = ((r0) * (0.13) + (0.12));
  const double r5 = (r0 * r3);
  const double r6 = (r0 * fk_s61);
  const double r7 = (fk_s57 * r3);
  R[0] = r5;
  R[1] = r2;
  R[2] = r6;
  R[3] = r7;
  R[4] = r0;
  R[5] = t34;
  R[6] = (-(fk_s61));
  R[8] = r3;
  p[0] = t36;
  p[1] = t35;
  // Jacobian (6 x 12)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  const double t38 = (0 - t35);
  const double t37 = (t36 - 0.12);
  const double t39 = ((r2) * (((fk_s57) * (0.13) + ((-(t35))))) + ((-((r0 * (t36 - t36))))));
  J[0 * 12 + 0] = ((r5) * (t38) + ((r7 * t37)));
  J[0 * 12 + 1] = ((-(fk_s61)) * t39);
  J[1 * 12 + 0] = ((r2) * (t38) + ((r0 * t37)));
  J[2 * 12 + 0] = ((r6) * (t38) + ((t34 * t37)));
  J[2 * 12 + 1] = (r3 * t39);
  J[3 * 12 + 0] = (-(fk_s61));
  J[3 * 12 + 1] = ((r5) * (r2) + ((r7 * r0)));
  J[4 * 12 + 1] = ((r2) * (r2) + ((r0 * r0)));
  J[5 * 12 + 0] = r3;
  J[5 * 12 + 1] = ((r6) * (r2) + ((t34 * r0)));
  }
}
#ifdef __cplusplus
}
#endif

