// Generated by fastfk for robot: six_dof
// Task: spatial:link5[0]; spatial:link5[1]; spatial:link5[2]; spatial:link5[3]; spatial:link5[4]; spatial:link5[5]
#include "fk_jacobian.hpp"

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: link5
  {
  double fk_s33 = 0, fk_c32 = 0;
  fastfk_fast_sincos(q[0], &fk_s33, &fk_c32);
  const double r0 = fk_c32;
  double fk_s37 = 0, fk_c36 = 0;
  fastfk_fast_sincos(q[1], &fk_s37, &fk_c36);
  const double r3 = fk_c36;
  const double t126 = (fk_s33 * r3);
  const double t140 = ((fk_s33) * (0.14999999999999999) + ((t126 * 0.14999999999999999)));
  const double t123 = (-(fk_s37));
  double fk_s46 = 0, fk_c45 = 0;
  fastfk_fast_sincos(q[2], &fk_s46, &fk_c45);
  const double r7 = fk_c45;
  const double t131 = (t123 * r7);
  const double t145 = ((t123) * (0.14999999999999999) + ((t131 * 0.12)));
  const double t143 = ((t126) * (r7) + ((r0 * fk_s46)));
  double fk_s69 = 0, fk_c68 = 0;
  fastfk_fast_sincos(q[3], &fk_s69, &fk_c68);
  const double r10 = fk_c68;
  const double t127 = (fk_s33 * fk_s37);
  const double r12 = (-(fk_s69));
  const double t148 = ((t143) * (r10) + ((t127 * r12)));
  const double t153 = ((t148) * (0.10000000000000001) + (((t143) * (0.12) + (t140))));
  const double r2 = (-(fk_s33));
  const double r5 = (r0 * r3);
  const double r9 = (-(fk_s46));
  const double t142 = ((r5) * (r9) + ((r2 * r7)));
  const double t150 = ((t131) * (r10) + ((r3 * r12)));
  const double t154 = ((t150) * (0.10000000000000001) + (t145));
  const double t139 = ((r0) * (0.14999999999999999) + ((r5 * 0.14999999999999999)));
  const double t141 = ((r5) * (r7) + ((r2 * fk_s46)));
  const double r6 = (r0 * fk_s37);
  const double t146 = ((t141) * (r10) + ((r6 * r12)));
  const double t152 = ((t146) * (0.10000000000000001) + (((t141) * (0.12) + (t139))));
  const double t132 = (t123 * r9);
  const double t151 = ((t131) * (fk_s69) + ((r3 * r10)));
  double fk_s97 = 0, fk_c96 = 0;
  fastfk_fast_sincos(q[4], &fk_s97, &fk_c96);
  const double r13 = fk_c96;
  const double t159 = ((t150) * (r13) + ((t132 * fk_s97)));
  const double r15 = (-(fk_s97));
  const double t160 = ((t150) * (r15) + ((t132 * r13)));
  const double t144 = ((t126) * (r9) + ((r0 * r7)));
  const double t149 = ((t143) * (fk_s69) + ((t127 * r10)));
  const double t147 = ((t141) * (fk_s69) + ((r6 * r10)));
  const double t155 = ((t146) * (r13) + ((t142 * fk_s97)));
  const double t156 = ((t146) * (r15) + ((t142 * r13)));
  const double t157 = ((t148) * (r13) + ((t144 * fk_s97)));
  const double t158 = ((t148) * (r15) + ((t144 * r13)));
  R[0] = t155;
  R[1] = t156;
  R[2] = t147;
  R[3] = t157;
  R[4] = t158;
  R[5] = t149;
  R[6] = t159;
  R[7] = t160;
  R[8] = t151;
  p[0] = t152;
  p[1] = t153;
  p[2] = t154;
  // Jacobian (6 x 6)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  const double t162 = (0 - t153);
  const double t165 = ((r2) * ((t153 - (fk_s33 * 0.14999999999999999))) + ((-((r0 * (t152 - (r0 * 0.14999999999999999)))))));
  const double t163 = (r0 * t154);
  const double t164 = (0 - (r2 * t154));
  const double t168 = ((r6) * ((t153 - t140)) + ((-((t127 * (t152 - t139))))));
  const double t161 = (t154 - (t123 * 0.14999999999999999));
  const double t166 = ((t127) * (t161) + ((-((r3 * (t153 - t140))))));
  const double t167 = ((r3) * ((t152 - t139)) + ((-((r6 * t161)))));
  const double t169 = (t153 - ((t143) * (0.12) + (t140)));
  const double t171 = (t152 - ((t141) * (0.12) + (t139)));
  const double t173 = ((t142) * (t169) + ((-((t144 * t171)))));
  const double t170 = ((t144) * ((t154 - t145)) + ((-((t132 * t169)))));
  const double t172 = ((t132) * (t171) + ((-((t142 * (t154 - t145))))));
  const double t176 = ((t147) * ((t153 - t153)) + ((-((t149 * (t152 - t152))))));
  const double t174 = ((t149) * ((t154 - t154)) + ((-((t151 * (t153 - t153))))));
  const double t175 = ((t151) * ((t152 - t152)) + ((-((t147 * (t154 - t154))))));
  J[0 * 6 + 0] = ((t155) * (t162) + ((t157 * t152)));
  J[0 * 6 + 1] = ((t159) * (t165) + (((t155) * (t163) + ((t157 * t164)))));
  J[0 * 6 + 2] = ((t159) * (t168) + (((t155) * (t166) + ((t157 * t167)))));
  J[0 * 6 + 3] = ((t159) * (t173) + (((t155) * (t170) + ((t157 * t172)))));
  J[0 * 6 + 4] = ((t159) * (t176) + (((t155) * (t174) + ((t157 * t175)))));
  J[1 * 6 + 0] = ((t156) * (t162) + ((t158 * t152)));
  J[1 * 6 + 1] = ((t160) * (t165) + (((t156) * (t163) + ((t158 * t164)))));
  J[1 * 6 + 2] = ((t160) * (t168) + (((t156) * (t166) + ((t158 * t167)))));
  J[1 * 6 + 3] = ((t160) * (t173) + (((t156) * (t170) + ((t158 * t172)))));
  J[1 * 6 + 4] = ((t160) * (t176) + (((t156) * (t174) + ((t158 * t175)))));
  J[2 * 6 + 0] = ((t147) * (t162) + ((t149 * t152)));
  J[2 * 6 + 1] = ((t151) * (t165) + (((t147) * (t163) + ((t149 * t164)))));
  J[2 * 6 + 2] = ((t151) * (t168) + (((t147) * (t166) + ((t149 * t167)))));
  J[2 * 6 + 3] = ((t151) * (t173) + (((t147) * (t170) + ((t149 * t172)))));
  J[2 * 6 + 4] = ((t151) * (t176) + (((t147) * (t174) + ((t149 * t175)))));
  J[3 * 6 + 0] = t159;
  J[3 * 6 + 1] = ((t155) * (r2) + ((t157 * r0)));
  J[3 * 6 + 2] = ((t159) * (r3) + (((t155) * (r6) + ((t157 * t127)))));
  J[3 * 6 + 3] = ((t159) * (t132) + (((t155) * (t142) + ((t157 * t144)))));
  J[3 * 6 + 4] = ((t159) * (t151) + (((t155) * (t147) + ((t157 * t149)))));
  J[4 * 6 + 0] = t160;
  J[4 * 6 + 1] = ((t156) * (r2) + ((t158 * r0)));
  J[4 * 6 + 2] = ((t160) * (r3) + (((t156) * (r6) + ((t158 * t127)))));
  J[4 * 6 + 3] = ((t160) * (t132) + (((t156) * (t142) + ((t158 * t144)))));
  J[4 * 6 + 4] = ((t160) * (t151) + (((t156) * (t147) + ((t158 * t149)))));
  J[5 * 6 + 0] = t151;
  J[5 * 6 + 1] = ((t147) * (r2) + ((t149 * r0)));
  J[5 * 6 + 2] = ((t151) * (r3) + (((t147) * (r6) + ((t149 * t127)))));
  J[5 * 6 + 3] = ((t151) * (t132) + (((t147) * (t142) + ((t149 * t144)))));
  J[5 * 6 + 4] = ((t151) * (t151) + (((t147) * (t147) + ((t149 * t149)))));
  }
}
#ifdef __cplusplus
}
#endif

