#pragma once
// Generated by fastfk for robot: panda
// Task: spatial:panda_rightfinger[0]; spatial:panda_rightfinger[1]; spatial:panda_rightfinger[2]; spatial:panda_rightfinger[3]; spatial:panda_rightfinger[4]; spatial:panda_rightfinger[5]
// FASTFK_TASK_ABI: spatial_local
// FASTFK_CODEGEN: sincos,fast-trig,no-fma,min-regs,budget=16,materialize
// FASTFK_CXX_FLAGS: -O2 -std=c++17 -march=native -ffp-contract=off
#include <cmath>
#include "fk_fast_math.hpp"
#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R /*[9]*/,
    double* p /*[3]*/,
    double* J /*[6 x 9] row-major*/);
#ifdef __cplusplus
}
#endif
