// Generated by fastfk for robot: chain12
// Task: spatial:link4[0]; spatial:link4[1]; spatial:link4[2]; spatial:link4[3]; spatial:link4[4]; spatial:link4[5]
#include "fk_jacobian.hpp"

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: link4
  {
  double fk_s57 = 0, fk_c56 = 0;
  fastfk_fast_sincos(q[0], &fk_s57, &fk_c56);
  const double r0 = fk_c56;
  double fk_s61 = 0, fk_c60 = 0;
  fastfk_fast_sincos(q[1], &fk_s61, &fk_c60);
  const double r3 = fk_c60;
  const double r5 = (r0 * r3);
  const double t106 = ((r5) * (0.14000000000000001) + (((r0) * (0.13) + (0.12))));
  const double t96 = (fk_s57 * r3);
  const double t107 = ((fk_s57) * (0.13) + ((t96 * 0.14000000000000001)));
  const double t93 = (-(fk_s61));
  double fk_s72 = 0, fk_c71 = 0;
  fastfk_fast_sincos(q[2], &fk_s72, &fk_c71);
  const double r7 = fk_c71;
  const double t101 = (t93 * r7);
  const double t114 = ((t93) * (0.14000000000000001) + ((t101 * 0.14999999999999999)));
  const double t110 = ((t96) * (r7) + ((r0 * fk_s72)));
  const double t113 = ((t110) * (0.14999999999999999) + (t107));
  const double r2 = (-(fk_s57));
  const double t97 = (fk_s57 * fk_s61);
  const double r13 = ((r5) * (r7) + ((r2 * fk_s72)));
  const double t112 = ((r13) * (0.14999999999999999) + (t106));
  const double r6 = (r0 * fk_s61);
  const double r9 = (-(fk_s72));
  const double t102 = (t93 * r9);
  double fk_s95 = 0, fk_c94 = 0;
  fastfk_fast_sincos(q[3], &fk_s95, &fk_c94);
  const double r11 = fk_s95;
  const double t120 = ((t101) * (r11) + ((r3 * fk_c94)));
  const double r12 = (-(r11));
  const double t119 = ((t101) * (fk_c94) + ((r3 * r12)));
  const double r14 = ((r5) * (r9) + ((r2 * r7)));
  const double r15 = ((t96) * (r9) + ((r0 * r7)));
  const double t115 = ((r13) * (fk_c94) + ((r6 * r12)));
  const double t116 = ((r13) * (r11) + ((r6 * fk_c94)));
  const double t117 = ((t110) * (fk_c94) + ((t97 * r12)));
  const double t118 = ((t110) * (r11) + ((t97 * fk_c94)));
  R[0] = t115;
  R[1] = r14;
  R[2] = t116;
  R[3] = t117;
  R[4] = r15;
  R[5] = t118;
  R[6] = t119;
  R[7] = t102;
  R[8] = t120;
  p[0] = t112;
  p[1] = t113;
  p[2] = t114;
  // Jacobian (6 x 12)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  const double t123 = (0 - t113);
  const double t121 = (t112 - 0.12);
  const double t126 = ((r2) * ((t113 - (fk_s57 * 0.13))) + ((-((r0 * (t112 - ((r0) * (0.13) + (0.12))))))));
  const double t124 = (r0 * t114);
  const double t125 = (0 - (r2 * t114));
  const double t129 = ((r6) * ((t113 - t107)) + ((-((t97 * (t112 - t106))))));
  const double t122 = (t114 - (t93 * 0.14000000000000001));
  const double t127 = ((t97) * (t122) + ((-((r3 * (t113 - t107))))));
  const double t128 = ((r3) * ((t112 - t106)) + ((-((r6 * t122)))));
  const double t132 = ((r14) * ((t113 - t113)) + ((-((r15 * (t112 - t112))))));
  const double t130 = ((r15) * ((t114 - t114)) + ((-((t102 * (t113 - t113))))));
  const double t131 = ((t102) * ((t112 - t112)) + ((-((r14 * (t114 - t114))))));
  J[0 * 12 + 0] = ((t115) * (t123) + ((t117 * t121)));
  J[0 * 12 + 1] = ((t119) * (t126) + (((t115) * (t124) + ((t117 * t125)))));
  J[0 * 12 + 2] = ((t119) * (t129) + (((t115) * (t127) + ((t117 * t128)))));
  J[0 * 12 + 3] = ((t119) * (t132) + (((t115) * (t130) + ((t117 * t131)))));
  J[1 * 12 + 0] = ((r14) * (t123) + ((r15 * t121)));
  J[1 * 12 + 1] = ((t102) * (t126) + (((r14) * (t124) + ((r15 * t125)))));
  J[1 * 12 + 2] = ((t102) * (t129) + (((r14) * (t127) + ((r15 * t128)))));
  J[1 * 12 + 3] = ((t102) * (t132) + (((r14) * (t130) + ((r15 * t131)))));
  J[2 * 12 + 0] = ((t116) * (t123) + ((t118 * t121)));
  J[2 * 12 + 1] = ((t120) * (t126) + (((t116) * (t124) + ((t118 * t125)))));
  J[2 * 12 + 2] = ((t120) * (t129) + (((t116) * (t127) + ((t118 * t128)))));
  J[2 * 12 + 3] = ((t120) * (t132) + (((t116) * (t130) + ((t118 * t131)))));
  J[3 * 12 + 0] = t119;
  J[3 * 12 + 1] = ((t115) * (r2) + ((t117 * r0)));
  J[3 * 12 + 2] = ((t119) * (r3) + (((t115) * (r6) + ((t117 * t97)))));
  J[3 * 12 + 3] = ((t119) * (t102) + (((t115) * (r14) + ((t117 * r15)))));
  J[4 * 12 + 0] = t102;
  J[4 * 12 + 1] = ((r14) * (r2) + ((r15 * r0)));
  J[4 * 12 + 2] = ((t102) * (r3) + (((r14) * (r6) + ((r15 * t97)))));
  J[4 * 12 + 3] = ((t102) * (t102) + (((r14) * (r14) + ((r15 * r15)))));
  J[5 * 12 + 0] = t120;
  J[5 * 12 + 1] = ((t116) * (r2) + ((t118 * r0)));
  J[5 * 12 + 2] = ((t120) * (r3) + (((t116) * (r6) + ((t118 * t97)))));
  J[5 * 12 + 3] = ((t120) * (t102) + (((t116) * (r14) + ((t118 * r15)))));
  }
}
#ifdef __cplusplus
}
#endif

