// Generated by fastfk for robot: chain12
// Task: spatial:link3[0]; spatial:link3[1]; spatial:link3[2]; spatial:link3[3]; spatial:link3[4]; spatial:link3[5]
#include "fk_jacobian.hpp"

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: link3
  {
  double fk_s57 = 0, fk_c56 = 0;
  fastfk_fast_sincos(q[0], &fk_s57, &fk_c56);
  const double r0 = fk_c56;
  double fk_s61 = 0, fk_c60 = 0;
  fastfk_fast_sincos(q[1], &fk_s61, &fk_c60);
  const double t62 = fk_s61;
  const double t63 = (-(t62));
  const double t73 = (t63 * 0.14000000000000001);
  const double r2 = (-(fk_s57));
  double fk_s72 = 0, fk_c71 = 0;
  fastfk_fast_sincos(q[2], &fk_s72, &fk_c71);
  const double r8 = fk_c71;
  const double t71 = (t63 * r8);
  const double r4 = (r0 * fk_c60);
  const double r6 = (fk_s57 * fk_c60);
  const double t75 = ((fk_s57) * (0.13) + ((r6 * 0.14000000000000001)));
  const double r5 = (r0 * t62);
  const double r7 = (fk_s57 * t62);
  const double r9 = (-(fk_s72));
  const double t72 = (t63 * r9);
  const double t74 = ((r4) * (0.14000000000000001) + (((r0) * (0.13) + (0.12))));
  const double r10 = ((r4) * (r8) + ((r2 * fk_s72)));
  const double r11 = ((r4) * (r9) + ((r2 * r8)));
  const double r12 = ((r6) * (r8) + ((r0 * fk_s72)));
  const double r13 = ((r6) * (r9) + ((r0 * r8)));
  R[0] = r10;
  R[1] = r11;
  R[2] = r5;
  R[3] = r12;
  R[4] = r13;
  R[5] = r7;
  R[6] = t71;
  R[7] = t72;
  R[8] = fk_c60;
  p[0] = t74;
  p[1] = t75;
  p[2] = t73;
  // Jacobian (6 x 12)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  const double t81 = (0 - t75);
  const double t80 = (t74 - 0.12);
  const double t84 = ((r2) * ((t75 - (fk_s57 * 0.13))) + ((-((r0 * (t74 - ((r0) * (0.13) + (0.12))))))));
  const double t82 = (r0 * t73);
  const double t83 = (0 - (r2 * t73));
  const double t88 = ((r5) * ((t75 - t75)) + ((-((r7 * (t74 - t74))))));
  const double t85 = ((t63) * (0.14000000000000001) + ((-(t73))));
  const double t86 = ((r7) * (t85) + ((-((fk_c60 * (t75 - t75))))));
  const double t87 = ((fk_c60) * ((t74 - t74)) + ((-((r5 * t85)))));
  J[0 * 12 + 0] = ((r10) * (t81) + ((r12 * t80)));
  J[0 * 12 + 1] = ((t71) * (t84) + (((r10) * (t82) + ((r12 * t83)))));
  J[0 * 12 + 2] = ((t71) * (t88) + (((r10) * (t86) + ((r12 * t87)))));
  J[1 * 12 + 0] = ((r11) * (t81) + ((r13 * t80)));
  J[1 * 12 + 1] = ((t72) * (t84) + (((r11) * (t82) + ((r13 * t83)))));
  J[1 * 12 + 2] = ((t72) * (t88) + (((r11) * (t86) + ((r13 * t87)))));
  J[2 * 12 + 0] = ((r5) * (t81) + ((r7 * t80)));
  J[2 * 12 + 1] = ((fk_c60) * (t84) + (((r5) * (t82) + ((r7 * t83)))));
  J[2 * 12 + 2] = ((fk_c60) * (t88) + (((r5) * (t86) + ((r7 * t87)))));
  J[3 * 12 + 0] = t71;
  J[3 * 12 + 1] = ((r10) * (r2) + ((r12 * r0)));
  J[3 * 12 + 2] = ((t71) * (fk_c60) + (((r10) * (r5) + ((r12 * r7)))));
  J[4 * 12 + 0] = t72;
  J[4 * 12 + 1] = ((r11) * (r2) + ((r13 * r0)));
  J[4 * 12 + 2] = ((t72) * (fk_c60) + (((r11) * (r5) + ((r13 * r7)))));
  J[5 * 12 + 0] = fk_c60;
  J[5 * 12 + 1] = ((r5) * (r2) + ((r7 * r0)));
  J[5 * 12 + 2] = ((fk_c60) * (fk_c60) + (((r5) * (r5) + ((r7 * r7)))));
  }
}
#ifdef __cplusplus
}
#endif

