// Generated by fastfk for robot: ur3e_robot
// Task: spatial:base[0]; spatial:base[1]; spatial:base[2]; spatial:base[3]; spatial:base[4]; spatial:base[5]
#include "fk_jacobian.hpp"

// q-invariant R/p (call once; not written by fastfk_task).
void fastfk_init_static_frames(double* R, double* p) {
  // base
  R[0] = -1.0;
  R[1] = 0.0;
  R[2] = 0.0;
  R[3] = 0.0;
  R[4] = -1.0;
  R[5] = 0.0;
  R[6] = 0.0;
  R[7] = 0.0;
  R[8] = 1.0;
  p[0] = 0.0;
  p[1] = 0.0;
  p[2] = 0.0;
}

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: base (static — fastfk_init_static_frames)
  // Jacobian (6 x 6)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
}
#ifdef __cplusplus
}
#endif

