// Generated by fastfk for robot: chain12
// Task: spatial:link5[0]; spatial:link5[1]; spatial:link5[2]; spatial:link5[3]; spatial:link5[4]; spatial:link5[5]
#include "fk_jacobian.hpp"

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: link5
  {
  double fk_s57 = 0, fk_c56 = 0;
  fastfk_fast_sincos(q[0], &fk_s57, &fk_c56);
  const double r0 = fk_c56;
  double fk_s61 = 0, fk_c60 = 0;
  fastfk_fast_sincos(q[1], &fk_s61, &fk_c60);
  const double r3 = fk_c60;
  const double r5 = (r0 * r3);
  const double t139 = ((r5) * (0.14000000000000001) + (((r0) * (0.13) + (0.12))));
  const double t126 = (fk_s57 * r3);
  const double t140 = ((fk_s57) * (0.13) + ((t126 * 0.14000000000000001)));
  const double t123 = (-(fk_s61));
  double fk_s72 = 0, fk_c71 = 0;
  fastfk_fast_sincos(q[2], &fk_s72, &fk_c71);
  const double r7 = fk_c71;
  const double t131 = (t123 * r7);
  const double t145 = ((t123) * (0.14000000000000001) + ((t131 * 0.14999999999999999)));
  const double t143 = ((t126) * (r7) + ((r0 * fk_s72)));
  double fk_s95 = 0, fk_c94 = 0;
  fastfk_fast_sincos(q[3], &fk_s95, &fk_c94);
  const double r10 = fk_c94;
  const double t127 = (fk_s57 * fk_s61);
  const double r12 = (-(fk_s95));
  const double t148 = ((t143) * (r10) + ((t127 * r12)));
  const double t153 = ((t148) * (0.12) + (((t143) * (0.14999999999999999) + (t140))));
  const double r2 = (-(fk_s57));
  const double r9 = (-(fk_s72));
  const double t142 = ((r5) * (r9) + ((r2 * r7)));
  const double t150 = ((t131) * (r10) + ((r3 * r12)));
  const double t154 = ((t150) * (0.12) + (t145));
  const double t151 = ((t131) * (fk_s95) + ((r3 * r10)));
  const double t141 = ((r5) * (r7) + ((r2 * fk_s72)));
  const double r6 = (r0 * fk_s61);
  const double t146 = ((t141) * (r10) + ((r6 * r12)));
  const double t152 = ((t146) * (0.12) + (((t141) * (0.14999999999999999) + (t139))));
  const double t132 = (t123 * r9);
  double fk_s122 = 0, fk_c121 = 0;
  fastfk_fast_sincos(q[4], &fk_s122, &fk_c121);
  const double r14 = fk_s122;
  const double r15 = (-(r14));
  const double t160 = ((t150) * (r15) + ((t132 * fk_c121)));
  const double t159 = ((t150) * (fk_c121) + ((t132 * r14)));
  const double t144 = ((t126) * (r9) + ((r0 * r7)));
  const double t149 = ((t143) * (fk_s95) + ((t127 * r10)));
  const double t147 = ((t141) * (fk_s95) + ((r6 * r10)));
  const double t155 = ((t146) * (fk_c121) + ((t142 * r14)));
  const double t156 = ((t146) * (r15) + ((t142 * fk_c121)));
  const double t157 = ((t148) * (fk_c121) + ((t144 * r14)));
  const double t158 = ((t148) * (r15) + ((t144 * fk_c121)));
  R[0] = t155;
  R[1] = t156;
  R[2] = t147;
  R[3] = t157;
  R[4] = t158;
  R[5] = t149;
  R[6] = t159;
  R[7] = t160;
  R[8] = t151;
  p[0] = t152;
  p[1] = t153;
  p[2] = t154;
  // Jacobian (6 x 12)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  const double t163 = (0 - t153);
  const double t161 = (t152 - 0.12);
  const double t166 = ((r2) * ((t153 - (fk_s57 * 0.13))) + ((-((r0 * (t152 - ((r0) * (0.13) + (0.12))))))));
  const double t164 = (r0 * t154);
  const double t165 = (0 - (r2 * t154));
  const double t169 = ((r6) * ((t153 - t140)) + ((-((t127 * (t152 - t139))))));
  const double t162 = (t154 - (t123 * 0.14000000000000001));
  const double t167 = ((t127) * (t162) + ((-((r3 * (t153 - t140))))));
  const double t168 = ((r3) * ((t152 - t139)) + ((-((r6 * t162)))));
  const double t170 = (t153 - ((t143) * (0.14999999999999999) + (t140)));
  const double t172 = (t152 - ((t141) * (0.14999999999999999) + (t139)));
  const double t174 = ((t142) * (t170) + ((-((t144 * t172)))));
  const double t171 = ((t144) * ((t154 - t145)) + ((-((t132 * t170)))));
  const double t173 = ((t132) * (t172) + ((-((t142 * (t154 - t145))))));
  const double t177 = ((t147) * ((t153 - t153)) + ((-((t149 * (t152 - t152))))));
  const double t175 = ((t149) * ((t154 - t154)) + ((-((t151 * (t153 - t153))))));
  const double t176 = ((t151) * ((t152 - t152)) + ((-((t147 * (t154 - t154))))));
  J[0 * 12 + 0] = ((t155) * (t163) + ((t157 * t161)));
  J[0 * 12 + 1] = ((t159) * (t166) + (((t155) * (t164) + ((t157 * t165)))));
  J[0 * 12 + 2] = ((t159) * (t169) + (((t155) * (t167) + ((t157 * t168)))));
  J[0 * 12 + 3] = ((t159) * (t174) + (((t155) * (t171) + ((t157 * t173)))));
  J[0 * 12 + 4] = ((t159) * (t177) + (((t155) * (t175) + ((t157 * t176)))));
  J[1 * 12 + 0] = ((t156) * (t163) + ((t158 * t161)));
  J[1 * 12 + 1] = ((t160) * (t166) + (((t156) * (t164) + ((t158 * t165)))));
  J[1 * 12 + 2] = ((t160) * (t169) + (((t156) * (t167) + ((t158 * t168)))));
  J[1 * 12 + 3] = ((t160) * (t174) + (((t156) * (t171) + ((t158 * t173)))));
  J[1 * 12 + 4] = ((t160) * (t177) + (((t156) * (t175) + ((t158 * t176)))));
  J[2 * 12 + 0] = ((t147) * (t163) + ((t149 * t161)));
  J[2 * 12 + 1] = ((t151) * (t166) + (((t147) * (t164) + ((t149 * t165)))));
  J[2 * 12 + 2] = ((t151) * (t169) + (((t147) * (t167) + ((t149 * t168)))));
  J[2 * 12 + 3] = ((t151) * (t174) + (((t147) * (t171) + ((t149 * t173)))));
  J[2 * 12 + 4] = ((t151) * (t177) + (((t147) * (t175) + ((t149 * t176)))));
  J[3 * 12 + 0] = t159;
  J[3 * 12 + 1] = ((t155) * (r2) + ((t157 * r0)));
  J[3 * 12 + 2] = ((t159) * (r3) + (((t155) * (r6) + ((t157 * t127)))));
  J[3 * 12 + 3] = ((t159) * (t132) + (((t155) * (t142) + ((t157 * t144)))));
  J[3 * 12 + 4] = ((t159) * (t151) + (((t155) * (t147) + ((t157 * t149)))));
  J[4 * 12 + 0] = t160;
  J[4 * 12 + 1] = ((t156) * (r2) + ((t158 * r0)));
  J[4 * 12 + 2] = ((t160) * (r3) + (((t156) * (r6) + ((t158 * t127)))));
  J[4 * 12 + 3] = ((t160) * (t132) + (((t156) * (t142) + ((t158 * t144)))));
  J[4 * 12 + 4] = ((t160) * (t151) + (((t156) * (t147) + ((t158 * t149)))));
  J[5 * 12 + 0] = t151;
  J[5 * 12 + 1] = ((t147) * (r2) + ((t149 * r0)));
  J[5 * 12 + 2] = ((t151) * (r3) + (((t147) * (r6) + ((t149 * t127)))));
  J[5 * 12 + 3] = ((t151) * (t132) + (((t147) * (t142) + ((t149 * t144)))));
  J[5 * 12 + 4] = ((t151) * (t151) + (((t147) * (t147) + ((t149 * t149)))));
  }
}
#ifdef __cplusplus
}
#endif

