// Generated by fastfk for robot: six_dof
// Task: spatial:link1[0]; spatial:link1[1]; spatial:link1[2]; spatial:link1[3]; spatial:link1[4]; spatial:link1[5]
#include "fk_jacobian.hpp"

// q-invariant R/p (call once; not written by fastfk_task).
void fastfk_init_static_frames(double* R, double* p) {
  // link1
  R[2] = 0.0;
  R[5] = 0.0;
  R[6] = 0.0;
  R[7] = 0.0;
  R[8] = 1.0;
  p[0] = 0.0;
  p[1] = 0.0;
  p[2] = 0.0;
}

// q-invariant Jacobian entries (call once; not written by fastfk_task).
void fastfk_init_static_jacobian(double* J) {
  J[5 * 6 + 0] = 1.0;
}

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: link1
  {
  double fk_s33 = 0, fk_c32 = 0;
  fastfk_fast_sincos(q[0], &fk_s33, &fk_c32);
  const double r0 = fk_c32;
  R[0] = r0;
  R[1] = (-(fk_s33));
  R[3] = fk_s33;
  R[4] = r0;
  // Jacobian (6 x 6)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  }
}
#ifdef __cplusplus
}
#endif

