// Generated by fastfk for robot: panda
// Task: spatial:panda_link0[0]; spatial:panda_link0[1]; spatial:panda_link0[2]; spatial:panda_link0[3]; spatial:panda_link0[4]; spatial:panda_link0[5]
#include "fk_jacobian.hpp"

// q-invariant R/p (call once; not written by fastfk_task).
void fastfk_init_static_frames(double* R, double* p) {
  // panda_link0
  R[0] = 1.0;
  R[1] = 0.0;
  R[2] = 0.0;
  R[3] = 0.0;
  R[4] = 1.0;
  R[5] = 0.0;
  R[6] = 0.0;
  R[7] = 0.0;
  R[8] = 1.0;
  p[0] = 0.0;
  p[1] = 0.0;
  p[2] = 0.0;
}

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: panda_link0 (static — fastfk_init_static_frames)
  // Jacobian (6 x 9)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
}
#ifdef __cplusplus
}
#endif

