// Generated by fastfk for robot: panda
// Task: spatial:panda_link7[0]; spatial:panda_link7[1]; spatial:panda_link7[2]; spatial:panda_link7[3]; spatial:panda_link7[4]; spatial:panda_link7[5]
#include "fk_jacobian.hpp"

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: panda_link7
  {
  double fk_s58 = 0, fk_c57 = 0;
  fastfk_fast_sincos(q[0], &fk_s58, &fk_c57);
  const double r0 = fk_c57;
  double fk_s61 = 0, fk_c60 = 0;
  fastfk_fast_sincos(q[1], &fk_s61, &fk_c60);
  const double r3 = fk_c60;
  const double t208 = (((-(r3))) * (-0.316) + (0.33300000000000002));
  const double r4 = (-(fk_s61));
  const double r5 = (r0 * r4);
  double fk_s71 = 0, fk_c70 = 0;
  fastfk_fast_sincos(q[2], &fk_s71, &fk_c70);
  const double r6 = fk_c70;
  const double r2 = (-(fk_s58));
  const double t209 = (((r0 * r3)) * (r6) + ((r2 * fk_s71)));
  const double t214 = ((r5) * (-0.316) + ((t209 * 0.082500000000000004)));
  const double t193 = (fk_s58 * r4);
  const double t211 = (((fk_s58 * r3)) * (r6) + ((r0 * fk_s71)));
  const double t215 = ((t193) * (-0.316) + ((t211 * 0.082500000000000004)));
  const double r8 = (-(fk_s71));
  const double t221 = (-((((fk_s58 * r3)) * (r8) + ((r0 * r6)))));
  const double t224 = (-((r4 * r8)));
  const double t213 = (r4 * r6);
  double fk_s96 = 0, fk_c95 = 0;
  fastfk_fast_sincos(q[3], &fk_s96, &fk_c95);
  const double r9 = fk_c95;
  const double t222 = ((t213) * (r9) + ((r3 * fk_s96)));
  const double r11 = (-(fk_s96));
  const double t223 = ((t213) * (r11) + ((r3 * r9)));
  const double t227 = (((t213) * (0.082500000000000004) + (t208)) + ((t222) * (-0.082500000000000004) + ((t223 * 0.38400000000000001))));
  const double t212 = (-(t193));
  const double t219 = ((t211) * (r9) + ((t212 * fk_s96)));
    double fk_s128 = 0, fk_c127 = 0;
    fastfk_fast_sincos(q[4], &fk_s128, &fk_c127);
  const double r13 = (-(fk_s128));
  const double t229 = (-(fk_c127));
  const double t235 = (-(((t219) * (r13) + ((t221 * t229)))));
  const double t237 = (-(((t222) * (r13) + ((t224 * t229)))));
  const double t231 = ((t222) * (fk_c127) + ((t224 * r13)));
  double fk_s163 = 0, fk_c162 = 0;
  fastfk_fast_sincos(q[5], &fk_s163, &fk_c162);
  const double r14 = fk_c162;
  const double t236 = ((t231) * (r14) + ((t223 * fk_s163)));
  const double t240 = ((t236) * (0.087999999999999995) + (t227));
  const double t218 = (-((((r0 * r3)) * (r8) + ((r2 * r6)))));
  const double t220 = ((t211) * (r11) + ((t212 * r9)));
  const double t226 = (t215 + ((t219) * (-0.082500000000000004) + ((t220 * 0.38400000000000001))));
  const double t210 = (-(r5));
  const double t216 = ((t209) * (r9) + ((t210 * fk_s96)));
  const double t233 = (-(((t216) * (r13) + ((t218 * t229)))));
  const double t217 = ((t209) * (r11) + ((t210 * r9)));
  const double t225 = (t214 + ((t216) * (-0.082500000000000004) + ((t217 * 0.38400000000000001))));
  const double t230 = ((t219) * (fk_c127) + ((t221 * r13)));
  const double t234 = ((t230) * (r14) + ((t220 * fk_s163)));
  const double t239 = ((t234) * (0.087999999999999995) + (t226));
  const double t228 = ((t216) * (fk_c127) + ((t218 * r13)));
  const double t232 = ((t228) * (r14) + ((t217 * fk_s163)));
  const double t238 = ((t232) * (0.087999999999999995) + (t225));
  double fk_s188 = 0, fk_c187 = 0;
  fastfk_fast_sincos(q[6], &fk_s188, &fk_c187);
  const double t205 = fk_c187;
  const double t247 = ((t236) * (t205) + ((t237 * fk_s188)));
  const double t207 = (-(fk_s188));
  const double t248 = ((t236) * (t207) + ((t237 * t205)));
  const double t204 = (-(fk_s163));
  const double t249 = (-(((t231) * (t204) + ((t223 * r14)))));
  const double t246 = (-(((t230) * (t204) + ((t220 * r14)))));
  const double t241 = ((t232) * (t205) + ((t233 * fk_s188)));
  const double t242 = ((t232) * (t207) + ((t233 * t205)));
  const double t243 = (-(((t228) * (t204) + ((t217 * r14)))));
  const double t244 = ((t234) * (t205) + ((t235 * fk_s188)));
  const double t245 = ((t234) * (t207) + ((t235 * t205)));
  R[0] = t241;
  R[1] = t242;
  R[2] = t243;
  R[3] = t244;
  R[4] = t245;
  R[5] = t246;
  R[6] = t247;
  R[7] = t248;
  R[8] = t249;
  p[0] = t238;
  p[1] = t239;
  p[2] = t240;
  // Jacobian (6 x 9)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  const double t254 = (0 - t239);
  const double t255 = ((r2) * (t239) + ((-((r0 * t238)))));
  const double t250 = (r0 * (t240 - 0.33300000000000002));
  const double t251 = (0 - (r2 * (t240 - 0.33300000000000002)));
  const double t253 = (t239 - (t193 * -0.316));
  const double t252 = (t238 - (r5 * -0.316));
  const double t256 = ((t210) * (t253) + ((-((t212 * t252)))));
  const double t257 = ((t212) * ((t240 - t208)) + ((-((r3 * t253)))));
  const double t258 = ((r3) * (t252) + ((-((t210 * (t240 - t208))))));
  const double t262 = ((t218) * ((t239 - t215)) + ((-((t221 * (t238 - t214))))));
  const double t259 = (t240 - ((t213) * (0.082500000000000004) + (t208)));
  const double t260 = ((t221) * (t259) + ((-((t224 * (t239 - t215))))));
  const double t261 = ((t224) * ((t238 - t214)) + ((-((t218 * t259)))));
  const double t263 = (t239 - t226);
  const double t264 = (t238 - t225);
  const double t265 = ((t217) * (t263) + ((-((t220 * t264)))));
  const double t266 = (t240 - t227);
  const double t267 = ((t220) * (t266) + ((-((t223 * t263)))));
  const double t268 = ((t223) * (t264) + ((-((t217 * t266)))));
  const double t269 = ((t233) * (t263) + ((-((t235 * t264)))));
  const double t270 = ((t235) * (t266) + ((-((t237 * t263)))));
  const double t271 = ((t237) * (t264) + ((-((t233 * t266)))));
  const double t272 = ((t243) * ((t239 - t239)) + ((-((t246 * (t238 - t238))))));
  const double t273 = ((t246) * ((t240 - t240)) + ((-((t249 * (t239 - t239))))));
  const double t274 = ((t249) * ((t238 - t238)) + ((-((t243 * (t240 - t240))))));
  J[0 * 9 + 0] = ((t241) * (t254) + ((t244 * t238)));
  J[0 * 9 + 1] = ((t247) * (t255) + (((t241) * (t250) + ((t244 * t251)))));
  J[0 * 9 + 2] = ((t247) * (t256) + (((t241) * (t257) + ((t244 * t258)))));
  J[0 * 9 + 3] = ((t247) * (t262) + (((t241) * (t260) + ((t244 * t261)))));
  J[0 * 9 + 4] = ((t247) * (t265) + (((t241) * (t267) + ((t244 * t268)))));
  J[0 * 9 + 5] = ((t247) * (t269) + (((t241) * (t270) + ((t244 * t271)))));
  J[0 * 9 + 6] = ((t247) * (t272) + (((t241) * (t273) + ((t244 * t274)))));
  J[1 * 9 + 0] = ((t242) * (t254) + ((t245 * t238)));
  J[1 * 9 + 1] = ((t248) * (t255) + (((t242) * (t250) + ((t245 * t251)))));
  J[1 * 9 + 2] = ((t248) * (t256) + (((t242) * (t257) + ((t245 * t258)))));
  J[1 * 9 + 3] = ((t248) * (t262) + (((t242) * (t260) + ((t245 * t261)))));
  J[1 * 9 + 4] = ((t248) * (t265) + (((t242) * (t267) + ((t245 * t268)))));
  J[1 * 9 + 5] = ((t248) * (t269) + (((t242) * (t270) + ((t245 * t271)))));
  J[1 * 9 + 6] = ((t248) * (t272) + (((t242) * (t273) + ((t245 * t274)))));
  J[2 * 9 + 0] = ((t243) * (t254) + ((t246 * t238)));
  J[2 * 9 + 1] = ((t249) * (t255) + (((t243) * (t250) + ((t246 * t251)))));
  J[2 * 9 + 2] = ((t249) * (t256) + (((t243) * (t257) + ((t246 * t258)))));
  J[2 * 9 + 3] = ((t249) * (t262) + (((t243) * (t260) + ((t246 * t261)))));
  J[2 * 9 + 4] = ((t249) * (t265) + (((t243) * (t267) + ((t246 * t268)))));
  J[2 * 9 + 5] = ((t249) * (t269) + (((t243) * (t270) + ((t246 * t271)))));
  J[2 * 9 + 6] = ((t249) * (t272) + (((t243) * (t273) + ((t246 * t274)))));
  J[3 * 9 + 0] = t247;
  J[3 * 9 + 1] = ((t241) * (r2) + ((t244 * r0)));
  J[3 * 9 + 2] = ((t247) * (r3) + (((t241) * (t210) + ((t244 * t212)))));
  J[3 * 9 + 3] = ((t247) * (t224) + (((t241) * (t218) + ((t244 * t221)))));
  J[3 * 9 + 4] = ((t247) * (t223) + (((t241) * (t217) + ((t244 * t220)))));
  J[3 * 9 + 5] = ((t247) * (t237) + (((t241) * (t233) + ((t244 * t235)))));
  J[3 * 9 + 6] = ((t247) * (t249) + (((t241) * (t243) + ((t244 * t246)))));
  J[4 * 9 + 0] = t248;
  J[4 * 9 + 1] = ((t242) * (r2) + ((t245 * r0)));
  J[4 * 9 + 2] = ((t248) * (r3) + (((t242) * (t210) + ((t245 * t212)))));
  J[4 * 9 + 3] = ((t248) * (t224) + (((t242) * (t218) + ((t245 * t221)))));
  J[4 * 9 + 4] = ((t248) * (t223) + (((t242) * (t217) + ((t245 * t220)))));
  J[4 * 9 + 5] = ((t248) * (t237) + (((t242) * (t233) + ((t245 * t235)))));
  J[4 * 9 + 6] = ((t248) * (t249) + (((t242) * (t243) + ((t245 * t246)))));
  J[5 * 9 + 0] = t249;
  J[5 * 9 + 1] = ((t243) * (r2) + ((t246 * r0)));
  J[5 * 9 + 2] = ((t249) * (r3) + (((t243) * (t210) + ((t246 * t212)))));
  J[5 * 9 + 3] = ((t249) * (t224) + (((t243) * (t218) + ((t246 * t221)))));
  J[5 * 9 + 4] = ((t249) * (t223) + (((t243) * (t217) + ((t246 * t220)))));
  J[5 * 9 + 5] = ((t249) * (t237) + (((t243) * (t233) + ((t246 * t235)))));
  J[5 * 9 + 6] = ((t249) * (t249) + (((t243) * (t243) + ((t246 * t246)))));
  }
}
#ifdef __cplusplus
}
#endif

