// Generated by fastfk for robot: panda
// Task: spatial:panda_link8[0]; spatial:panda_link8[1]; spatial:panda_link8[2]; spatial:panda_link8[3]; spatial:panda_link8[4]; spatial:panda_link8[5]
#include "fk_jacobian.hpp"

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: panda_link8
  {
  double fk_s58 = 0, fk_c57 = 0;
  fastfk_fast_sincos(q[0], &fk_s58, &fk_c57);
  const double r0 = fk_c57;
  double fk_s61 = 0, fk_c60 = 0;
  fastfk_fast_sincos(q[1], &fk_s61, &fk_c60);
  const double r3 = fk_c60;
  const double t211 = (((-(r3))) * (-0.316) + (0.33300000000000002));
  const double r4 = (-(fk_s61));
  const double r5 = (r0 * r4);
  double fk_s71 = 0, fk_c70 = 0;
  fastfk_fast_sincos(q[2], &fk_s71, &fk_c70);
  const double r6 = fk_c70;
  const double r2 = (-(fk_s58));
  const double t212 = (((r0 * r3)) * (r6) + ((r2 * fk_s71)));
  const double t217 = ((r5) * (-0.316) + ((t212 * 0.082500000000000004)));
  const double t196 = (fk_s58 * r4);
  const double t214 = (((fk_s58 * r3)) * (r6) + ((r0 * fk_s71)));
  const double t218 = ((t196) * (-0.316) + ((t214 * 0.082500000000000004)));
  const double r8 = (-(fk_s71));
  const double t224 = (-((((fk_s58 * r3)) * (r8) + ((r0 * r6)))));
  const double t227 = (-((r4 * r8)));
  const double t216 = (r4 * r6);
  double fk_s96 = 0, fk_c95 = 0;
  fastfk_fast_sincos(q[3], &fk_s96, &fk_c95);
  const double r9 = fk_c95;
  const double t225 = ((t216) * (r9) + ((r3 * fk_s96)));
  const double r11 = (-(fk_s96));
  const double t226 = ((t216) * (r11) + ((r3 * r9)));
  const double t230 = (((t216) * (0.082500000000000004) + (t211)) + ((t225) * (-0.082500000000000004) + ((t226 * 0.38400000000000001))));
  const double t215 = (-(t196));
  const double t222 = ((t214) * (r9) + ((t215 * fk_s96)));
    double fk_s128 = 0, fk_c127 = 0;
    fastfk_fast_sincos(q[4], &fk_s128, &fk_c127);
  const double r13 = (-(fk_s128));
  const double t232 = (-(fk_c127));
  const double t238 = (-(((t222) * (r13) + ((t224 * t232)))));
  const double t240 = (-(((t225) * (r13) + ((t227 * t232)))));
  const double t234 = ((t225) * (fk_c127) + ((t227 * r13)));
  double fk_s163 = 0, fk_c162 = 0;
  fastfk_fast_sincos(q[5], &fk_s163, &fk_c162);
  const double r15 = fk_s163;
  const double t207 = (-(r15));
  const double t249 = (-(((t234) * (t207) + ((t226 * fk_c162)))));
  const double t239 = ((t234) * (fk_c162) + ((t226 * r15)));
  const double t252 = ((t249) * (0.107) + (((t239) * (0.087999999999999995) + (t230))));
  const double t221 = (-((((r0 * r3)) * (r8) + ((r2 * r6)))));
  const double t223 = ((t214) * (r11) + ((t215 * r9)));
  const double t229 = (t218 + ((t222) * (-0.082500000000000004) + ((t223 * 0.38400000000000001))));
  const double t213 = (-(r5));
  const double t219 = ((t212) * (r9) + ((t213 * fk_s96)));
  const double t236 = (-(((t219) * (r13) + ((t221 * t232)))));
  const double t233 = ((t222) * (fk_c127) + ((t224 * r13)));
  const double t246 = (-(((t233) * (t207) + ((t223 * fk_c162)))));
  const double t237 = ((t233) * (fk_c162) + ((t223 * r15)));
  const double t251 = ((t246) * (0.107) + (((t237) * (0.087999999999999995) + (t229))));
  const double t220 = ((t212) * (r11) + ((t213 * r9)));
  const double t228 = (t217 + ((t219) * (-0.082500000000000004) + ((t220 * 0.38400000000000001))));
  const double t231 = ((t219) * (fk_c127) + ((t221 * r13)));
  const double t243 = (-(((t231) * (t207) + ((t220 * fk_c162)))));
  const double t235 = ((t231) * (fk_c162) + ((t220 * r15)));
  const double t250 = ((t243) * (0.107) + (((t235) * (0.087999999999999995) + (t228))));
  double fk_s188 = 0, fk_c187 = 0;
  fastfk_fast_sincos(q[6], &fk_s188, &fk_c187);
  const double t208 = fk_c187;
  const double t247 = ((t239) * (t208) + ((t240 * fk_s188)));
  const double t210 = (-(fk_s188));
  const double t248 = ((t239) * (t210) + ((t240 * t208)));
  const double t241 = ((t235) * (t208) + ((t236 * fk_s188)));
  const double t242 = ((t235) * (t210) + ((t236 * t208)));
  const double t244 = ((t237) * (t208) + ((t238 * fk_s188)));
  const double t245 = ((t237) * (t210) + ((t238 * t208)));
  R[0] = t241;
  R[1] = t242;
  R[2] = t243;
  R[3] = t244;
  R[4] = t245;
  R[5] = t246;
  R[6] = t247;
  R[7] = t248;
  R[8] = t249;
  p[0] = t250;
  p[1] = t251;
  p[2] = t252;
  // Jacobian (6 x 9)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  const double t257 = (0 - t251);
  const double t258 = ((r2) * (t251) + ((-((r0 * t250)))));
  const double t253 = (r0 * (t252 - 0.33300000000000002));
  const double t254 = (0 - (r2 * (t252 - 0.33300000000000002)));
  const double t256 = (t251 - (t196 * -0.316));
  const double t255 = (t250 - (r5 * -0.316));
  const double t259 = ((t213) * (t256) + ((-((t215 * t255)))));
  const double t260 = ((t215) * ((t252 - t211)) + ((-((r3 * t256)))));
  const double t261 = ((r3) * (t255) + ((-((t213 * (t252 - t211))))));
  const double t265 = ((t221) * ((t251 - t218)) + ((-((t224 * (t250 - t217))))));
  const double t262 = (t252 - ((t216) * (0.082500000000000004) + (t211)));
  const double t263 = ((t224) * (t262) + ((-((t227 * (t251 - t218))))));
  const double t264 = ((t227) * ((t250 - t217)) + ((-((t221 * t262)))));
  const double t266 = (t251 - t229);
  const double t267 = (t250 - t228);
  const double t268 = ((t220) * (t266) + ((-((t223 * t267)))));
  const double t269 = (t252 - t230);
  const double t270 = ((t223) * (t269) + ((-((t226 * t266)))));
  const double t271 = ((t226) * (t267) + ((-((t220 * t269)))));
  const double t272 = ((t236) * (t266) + ((-((t238 * t267)))));
  const double t273 = ((t238) * (t269) + ((-((t240 * t266)))));
  const double t274 = ((t240) * (t267) + ((-((t236 * t269)))));
  const double t275 = (t251 - ((t237) * (0.087999999999999995) + (t229)));
  const double t276 = (t250 - ((t235) * (0.087999999999999995) + (t228)));
  const double t277 = ((t243) * (t275) + ((-((t246 * t276)))));
  const double t278 = (t252 - ((t239) * (0.087999999999999995) + (t230)));
  const double t279 = ((t246) * (t278) + ((-((t249 * t275)))));
  const double t280 = ((t249) * (t276) + ((-((t243 * t278)))));
  J[0 * 9 + 0] = ((t241) * (t257) + ((t244 * t250)));
  J[0 * 9 + 1] = ((t247) * (t258) + (((t241) * (t253) + ((t244 * t254)))));
  J[0 * 9 + 2] = ((t247) * (t259) + (((t241) * (t260) + ((t244 * t261)))));
  J[0 * 9 + 3] = ((t247) * (t265) + (((t241) * (t263) + ((t244 * t264)))));
  J[0 * 9 + 4] = ((t247) * (t268) + (((t241) * (t270) + ((t244 * t271)))));
  J[0 * 9 + 5] = ((t247) * (t272) + (((t241) * (t273) + ((t244 * t274)))));
  J[0 * 9 + 6] = ((t247) * (t277) + (((t241) * (t279) + ((t244 * t280)))));
  J[1 * 9 + 0] = ((t242) * (t257) + ((t245 * t250)));
  J[1 * 9 + 1] = ((t248) * (t258) + (((t242) * (t253) + ((t245 * t254)))));
  J[1 * 9 + 2] = ((t248) * (t259) + (((t242) * (t260) + ((t245 * t261)))));
  J[1 * 9 + 3] = ((t248) * (t265) + (((t242) * (t263) + ((t245 * t264)))));
  J[1 * 9 + 4] = ((t248) * (t268) + (((t242) * (t270) + ((t245 * t271)))));
  J[1 * 9 + 5] = ((t248) * (t272) + (((t242) * (t273) + ((t245 * t274)))));
  J[1 * 9 + 6] = ((t248) * (t277) + (((t242) * (t279) + ((t245 * t280)))));
  J[2 * 9 + 0] = ((t243) * (t257) + ((t246 * t250)));
  J[2 * 9 + 1] = ((t249) * (t258) + (((t243) * (t253) + ((t246 * t254)))));
  J[2 * 9 + 2] = ((t249) * (t259) + (((t243) * (t260) + ((t246 * t261)))));
  J[2 * 9 + 3] = ((t249) * (t265) + (((t243) * (t263) + ((t246 * t264)))));
  J[2 * 9 + 4] = ((t249) * (t268) + (((t243) * (t270) + ((t246 * t271)))));
  J[2 * 9 + 5] = ((t249) * (t272) + (((t243) * (t273) + ((t246 * t274)))));
  J[2 * 9 + 6] = ((t249) * (t277) + (((t243) * (t279) + ((t246 * t280)))));
  J[3 * 9 + 0] = t247;
  J[3 * 9 + 1] = ((t241) * (r2) + ((t244 * r0)));
  J[3 * 9 + 2] = ((t247) * (r3) + (((t241) * (t213) + ((t244 * t215)))));
  J[3 * 9 + 3] = ((t247) * (t227) + (((t241) * (t221) + ((t244 * t224)))));
  J[3 * 9 + 4] = ((t247) * (t226) + (((t241) * (t220) + ((t244 * t223)))));
  J[3 * 9 + 5] = ((t247) * (t240) + (((t241) * (t236) + ((t244 * t238)))));
  J[3 * 9 + 6] = ((t247) * (t249) + (((t241) * (t243) + ((t244 * t246)))));
  J[4 * 9 + 0] = t248;
  J[4 * 9 + 1] = ((t242) * (r2) + ((t245 * r0)));
  J[4 * 9 + 2] = ((t248) * (r3) + (((t242) * (t213) + ((t245 * t215)))));
  J[4 * 9 + 3] = ((t248) * (t227) + (((t242) * (t221) + ((t245 * t224)))));
  J[4 * 9 + 4] = ((t248) * (t226) + (((t242) * (t220) + ((t245 * t223)))));
  J[4 * 9 + 5] = ((t248) * (t240) + (((t242) * (t236) + ((t245 * t238)))));
  J[4 * 9 + 6] = ((t248) * (t249) + (((t242) * (t243) + ((t245 * t246)))));
  J[5 * 9 + 0] = t249;
  J[5 * 9 + 1] = ((t243) * (r2) + ((t246 * r0)));
  J[5 * 9 + 2] = ((t249) * (r3) + (((t243) * (t213) + ((t246 * t215)))));
  J[5 * 9 + 3] = ((t249) * (t227) + (((t243) * (t221) + ((t246 * t224)))));
  J[5 * 9 + 4] = ((t249) * (t226) + (((t243) * (t220) + ((t246 * t223)))));
  J[5 * 9 + 5] = ((t249) * (t240) + (((t243) * (t236) + ((t246 * t238)))));
  J[5 * 9 + 6] = ((t249) * (t249) + (((t243) * (t243) + ((t246 * t246)))));
  }
}
#ifdef __cplusplus
}
#endif

