// Generated by fastfk for robot: ur3e_robot
// Task: spatial:wrist_1_link[0]; spatial:wrist_1_link[1]; spatial:wrist_1_link[2]; spatial:wrist_1_link[3]; spatial:wrist_1_link[4]; spatial:wrist_1_link[5]
#include "fk_jacobian.hpp"

// q-invariant R/p (call once; not written by fastfk_task).
void fastfk_init_static_frames(double* R, double* p) {
  // wrist_1_link
  R[8] = 0.0;
}

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: wrist_1_link
  {
  double fk_s42 = 0, fk_c41 = 0;
  fastfk_fast_sincos(q[0], &fk_s42, &fk_c41);
  const double r0 = fk_c41;
  const double r1 = (-(fk_s42));
  double fk_s48 = 0, fk_c47 = 0;
  fastfk_fast_sincos(q[1], &fk_s48, &fk_c47);
  const double r2 = fk_c47;
  const double r11 = (r1 * r2);
  double fk_s58 = 0, fk_c57 = 0;
  fastfk_fast_sincos(q[2], &fk_s58, &fk_c57);
  const double r4 = fk_c57;
  const double r12 = (r1 * (-(fk_s48)));
  const double r14 = ((r11) * (r4) + ((r12 * fk_s58)));
  const double t109 = ((r11) * (-0.24354999999999999) + (((r14) * (-0.2132) + ((r0 * 0.13105)))));
  const double t99 = ((-(r0)) * (-(fk_s48)));
  const double r10 = ((-(r0)) * r2);
  const double r6 = (-(fk_s58));
  const double t103 = ((r10) * (r6) + ((t99 * r4)));
  const double r13 = ((r10) * (r4) + ((t99 * fk_s58)));
  const double t108 = ((r10) * (-0.24354999999999999) + (((r13) * (-0.2132) + ((r1 * 0.13105)))));
  const double t107 = ((fk_s48) * (r6) + ((r2 * r4)));
  const double t106 = ((fk_s48) * (r4) + ((r2 * fk_s58)));
  const double t110 = ((t106) * (-0.2132) + (((fk_s48) * (-0.24354999999999999) + (0.15185000000000001))));
  double fk_s85 = 0, fk_c84 = 0;
  fastfk_fast_sincos(q[3], &fk_s85, &fk_c84);
  const double r7 = fk_c84;
  const double t115 = ((t106) * (r7) + ((t107 * fk_s85)));
  const double r9 = (-(fk_s85));
  const double t116 = ((t106) * (r9) + ((t107 * r7)));
  const double t105 = ((r11) * (r6) + ((r12 * r4)));
  const double t114 = ((r14) * (r9) + ((t105 * r7)));
  const double r15 = ((r13) * (r7) + ((t103 * fk_s85)));
  const double t112 = ((r13) * (r9) + ((t103 * r7)));
  const double t113 = ((r14) * (r7) + ((t105 * fk_s85)));
  R[0] = r15;
  R[1] = t112;
  R[2] = r1;
  R[3] = t113;
  R[4] = t114;
  R[5] = r0;
  R[6] = t115;
  R[7] = t116;
  p[0] = t108;
  p[1] = t109;
  p[2] = t110;
  // Jacobian (6 x 6)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  const double t117 = (0 - t109);
  const double t118 = ((r1) * (t109) + ((-((r0 * t108)))));
  const double t119 = (r0 * (t110 - 0.15185000000000001));
  const double t120 = (0 - (r1 * (t110 - 0.15185000000000001)));
  const double t122 = ((r1) * ((t109 - (r11 * -0.24354999999999999))) + ((-((r0 * (t108 - (r10 * -0.24354999999999999)))))));
  const double t121 = (t110 - ((fk_s48) * (-0.24354999999999999) + (0.15185000000000001)));
  const double t123 = (r0 * t121);
  const double t124 = (0 - (r1 * t121));
  const double t125 = ((r1) * ((t109 - t109)) + ((-((r0 * (t108 - t108))))));
  const double t126 = (r0 * (t110 - t110));
  const double t127 = (0 - (r1 * (t110 - t110)));
  const double t128 = ((r15) * (r1) + ((t113 * r0)));
  const double t129 = ((t112) * (r1) + ((t114 * r0)));
  const double t130 = ((r1) * (r1) + ((r0 * r0)));
  J[0 * 6 + 0] = ((r15) * (t117) + ((t113 * t108)));
  J[0 * 6 + 1] = ((t115) * (t118) + (((r15) * (t119) + ((t113 * t120)))));
  J[0 * 6 + 2] = ((t115) * (t122) + (((r15) * (t123) + ((t113 * t124)))));
  J[0 * 6 + 3] = ((t115) * (t125) + (((r15) * (t126) + ((t113 * t127)))));
  J[1 * 6 + 0] = ((t112) * (t117) + ((t114 * t108)));
  J[1 * 6 + 1] = ((t116) * (t118) + (((t112) * (t119) + ((t114 * t120)))));
  J[1 * 6 + 2] = ((t116) * (t122) + (((t112) * (t123) + ((t114 * t124)))));
  J[1 * 6 + 3] = ((t116) * (t125) + (((t112) * (t126) + ((t114 * t127)))));
  J[2 * 6 + 0] = ((r1) * (t117) + ((r0 * t108)));
  J[2 * 6 + 1] = ((r1) * (t119) + ((r0 * t120)));
  J[2 * 6 + 2] = ((r1) * (t123) + ((r0 * t124)));
  J[2 * 6 + 3] = ((r1) * (t126) + ((r0 * t127)));
  J[3 * 6 + 0] = t115;
  J[3 * 6 + 1] = t128;
  J[3 * 6 + 2] = t128;
  J[3 * 6 + 3] = t128;
  J[4 * 6 + 0] = t116;
  J[4 * 6 + 1] = t129;
  J[4 * 6 + 2] = t129;
  J[4 * 6 + 3] = t129;
  J[5 * 6 + 1] = t130;
  J[5 * 6 + 2] = t130;
  J[5 * 6 + 3] = t130;
  }
}
#ifdef __cplusplus
}
#endif

