// Generated by fastfk for robot: six_dof
// Task: spatial:link2[0]; spatial:link2[1]; spatial:link2[2]; spatial:link2[3]; spatial:link2[4]; spatial:link2[5]
#include "fk_jacobian.hpp"

// q-invariant R/p (call once; not written by fastfk_task).
void fastfk_init_static_frames(double* R, double* p) {
  // link2
  R[7] = 0.0;
  p[2] = 0.0;
}

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: link2
  {
  double fk_s33 = 0, fk_c32 = 0;
  fastfk_fast_sincos(q[0], &fk_s33, &fk_c32);
  const double r0 = fk_c32;
  const double t11 = (fk_s33 * 0.14999999999999999);
  const double r2 = (-(fk_s33));
  double fk_s37 = 0, fk_c36 = 0;
  fastfk_fast_sincos(q[1], &fk_s37, &fk_c36);
  const double r3 = fk_c36;
  const double t5 = (-(fk_s37));
  const double t10 = (r0 * 0.14999999999999999);
  const double r5 = (r0 * r3);
  const double r6 = (r0 * fk_s37);
  const double r7 = (fk_s33 * r3);
  const double r8 = (fk_s33 * fk_s37);
  R[0] = r5;
  R[1] = r2;
  R[2] = r6;
  R[3] = r7;
  R[4] = r0;
  R[5] = r8;
  R[6] = t5;
  R[8] = r3;
  p[0] = t10;
  p[1] = t11;
  // Jacobian (6 x 6)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  const double t12 = (0 - t11);
  const double t13 = (r7 * t10);
  const double t14 = ((r5) * (t12) + (t13));
  const double t19 = (-(t11));
  const double t20 = ((fk_s33) * (0.14999999999999999) + (t19));
  const double t21 = (-(t10));
  const double t22 = ((r0) * (0.14999999999999999) + (t21));
  const double t23 = (r0 * t22);
  const double t24 = (-(t23));
  const double t25 = ((r2) * (t20) + (t24));
  const double t26 = (t5 * t25);
  const double t15 = (r0 * t10);
  const double t16 = ((r2) * (t12) + (t15));
  const double t17 = (r8 * t10);
  const double t18 = ((r6) * (t12) + (t17));
  const double t27 = (r3 * t25);
  const double t28 = (r7 * r0);
  const double t29 = ((r5) * (r2) + (t28));
  const double t30 = (r0 * r0);
  const double t31 = ((r2) * (r2) + (t30));
  const double t32 = (r8 * r0);
  const double t33 = ((r6) * (r2) + (t32));
  J[0 * 6 + 0] = t14;
  J[0 * 6 + 1] = t26;
  J[1 * 6 + 0] = t16;
  J[2 * 6 + 0] = t18;
  J[2 * 6 + 1] = t27;
  J[3 * 6 + 0] = t5;
  J[3 * 6 + 1] = t29;
  J[4 * 6 + 1] = t31;
  J[5 * 6 + 0] = r3;
  J[5 * 6 + 1] = t33;
  }
}
#ifdef __cplusplus
}
#endif

