// Generated by fastfk for robot: panda_arm
// Task: spatial:panda_link6[0]; spatial:panda_link6[1]; spatial:panda_link6[2]; spatial:panda_link6[3]; spatial:panda_link6[4]; spatial:panda_link6[5]
#include "fk_jacobian.hpp"

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: panda_link6
  {
  double fk_s40 = 0, fk_c39 = 0;
  fastfk_fast_sincos(q[0], &fk_s40, &fk_c39);
  const double r0 = fk_c39;
  double fk_s44 = 0, fk_c43 = 0;
  fastfk_fast_sincos(q[1], &fk_s44, &fk_c43);
  const double r3 = fk_c43;
  const double t172 = (((-(r3))) * (-0.316) + (0.33300000000000002));
  const double r4 = (-(fk_s44));
  const double r5 = (r0 * r4);
  double fk_s54 = 0, fk_c53 = 0;
  fastfk_fast_sincos(q[2], &fk_s54, &fk_c53);
  const double r6 = fk_c53;
  const double r2 = (-(fk_s40));
  const double t173 = (((r0 * r3)) * (r6) + ((r2 * fk_s54)));
  const double t178 = ((r5) * (-0.316) + ((t173 * 0.082500000000000004)));
  const double t160 = (fk_s40 * r4);
  const double t175 = (((fk_s40 * r3)) * (r6) + ((r0 * fk_s54)));
  const double t179 = ((t160) * (-0.316) + ((t175 * 0.082500000000000004)));
  const double r8 = (-(fk_s54));
  const double t185 = (-((((fk_s40 * r3)) * (r8) + ((r0 * r6)))));
  const double t188 = (-((r4 * r8)));
  const double t177 = (r4 * r6);
  double fk_s79 = 0, fk_c78 = 0;
  fastfk_fast_sincos(q[3], &fk_s79, &fk_c78);
  const double r9 = fk_c78;
  const double t186 = ((t177) * (r9) + ((r3 * fk_s79)));
  const double r11 = (-(fk_s79));
  const double t187 = ((t177) * (r11) + ((r3 * r9)));
  const double t191 = (((t177) * (0.082500000000000004) + (t172)) + ((t186) * (-0.082500000000000004) + ((t187 * 0.38400000000000001))));
  const double t176 = (-(t160));
  const double t182 = (-((((r0 * r3)) * (r8) + ((r2 * r6)))));
  const double t183 = ((t175) * (r9) + ((t176 * fk_s79)));
  const double t184 = ((t175) * (r11) + ((t176 * r9)));
  const double t190 = (t179 + ((t183) * (-0.082500000000000004) + ((t184 * 0.38400000000000001))));
  const double t174 = (-(r5));
  const double t180 = ((t173) * (r9) + ((t174 * fk_s79)));
  const double t181 = ((t173) * (r11) + ((t174 * r9)));
  const double t189 = (t178 + ((t180) * (-0.082500000000000004) + ((t181 * 0.38400000000000001))));
  double fk_s111 = 0, fk_c110 = 0;
  fastfk_fast_sincos(q[4], &fk_s111, &fk_c110);
  const double r12 = fk_c110;
  const double r13 = (-(fk_s111));
  const double t195 = ((t186) * (r12) + ((t188 * r13)));
  const double t193 = (-(r12));
  const double t204 = (-(((t186) * (r13) + ((t188 * t193)))));
  double fk_s146 = 0, fk_c145 = 0;
  fastfk_fast_sincos(q[5], &fk_s146, &fk_c145);
  const double r14 = fk_c145;
  const double t202 = ((t195) * (r14) + ((t187 * fk_s146)));
  const double t171 = (-(fk_s146));
  const double t203 = ((t195) * (t171) + ((t187 * r14)));
  const double t192 = ((t180) * (r12) + ((t182 * r13)));
  const double t194 = ((t183) * (r12) + ((t185 * r13)));
  const double t201 = (-(((t183) * (r13) + ((t185 * t193)))));
  const double t196 = ((t192) * (r14) + ((t181 * fk_s146)));
  const double t197 = ((t192) * (t171) + ((t181 * r14)));
  const double t198 = (-(((t180) * (r13) + ((t182 * t193)))));
  const double t199 = ((t194) * (r14) + ((t184 * fk_s146)));
  const double t200 = ((t194) * (t171) + ((t184 * r14)));
  R[0] = t196;
  R[1] = t197;
  R[2] = t198;
  R[3] = t199;
  R[4] = t200;
  R[5] = t201;
  R[6] = t202;
  R[7] = t203;
  R[8] = t204;
  p[0] = t189;
  p[1] = t190;
  p[2] = t191;
  // Jacobian (6 x 7)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  const double t209 = (0 - t190);
  const double t210 = ((r2) * (t190) + ((-((r0 * t189)))));
  const double t205 = (r0 * (t191 - 0.33300000000000002));
  const double t206 = (0 - (r2 * (t191 - 0.33300000000000002)));
  const double t208 = (t190 - (t160 * -0.316));
  const double t207 = (t189 - (r5 * -0.316));
  const double t211 = ((t174) * (t208) + ((-((t176 * t207)))));
  const double t212 = ((t176) * ((t191 - t172)) + ((-((r3 * t208)))));
  const double t213 = ((r3) * (t207) + ((-((t174 * (t191 - t172))))));
  const double t217 = ((t182) * ((t190 - t179)) + ((-((t185 * (t189 - t178))))));
  const double t214 = (t191 - ((t177) * (0.082500000000000004) + (t172)));
  const double t215 = ((t185) * (t214) + ((-((t188 * (t190 - t179))))));
  const double t216 = ((t188) * ((t189 - t178)) + ((-((t182 * t214)))));
  const double t218 = (t190 - t190);
  const double t219 = (t189 - t189);
  const double t220 = ((t181) * (t218) + ((-((t184 * t219)))));
  const double t221 = (t191 - t191);
  const double t222 = ((t184) * (t221) + ((-((t187 * t218)))));
  const double t223 = ((t187) * (t219) + ((-((t181 * t221)))));
  const double t224 = ((t198) * (t218) + ((-((t201 * t219)))));
  const double t225 = ((t201) * (t221) + ((-((t204 * t218)))));
  const double t226 = ((t204) * (t219) + ((-((t198 * t221)))));
  J[0 * 7 + 0] = ((t196) * (t209) + ((t199 * t189)));
  J[0 * 7 + 1] = ((t202) * (t210) + (((t196) * (t205) + ((t199 * t206)))));
  J[0 * 7 + 2] = ((t202) * (t211) + (((t196) * (t212) + ((t199 * t213)))));
  J[0 * 7 + 3] = ((t202) * (t217) + (((t196) * (t215) + ((t199 * t216)))));
  J[0 * 7 + 4] = ((t202) * (t220) + (((t196) * (t222) + ((t199 * t223)))));
  J[0 * 7 + 5] = ((t202) * (t224) + (((t196) * (t225) + ((t199 * t226)))));
  J[1 * 7 + 0] = ((t197) * (t209) + ((t200 * t189)));
  J[1 * 7 + 1] = ((t203) * (t210) + (((t197) * (t205) + ((t200 * t206)))));
  J[1 * 7 + 2] = ((t203) * (t211) + (((t197) * (t212) + ((t200 * t213)))));
  J[1 * 7 + 3] = ((t203) * (t217) + (((t197) * (t215) + ((t200 * t216)))));
  J[1 * 7 + 4] = ((t203) * (t220) + (((t197) * (t222) + ((t200 * t223)))));
  J[1 * 7 + 5] = ((t203) * (t224) + (((t197) * (t225) + ((t200 * t226)))));
  J[2 * 7 + 0] = ((t198) * (t209) + ((t201 * t189)));
  J[2 * 7 + 1] = ((t204) * (t210) + (((t198) * (t205) + ((t201 * t206)))));
  J[2 * 7 + 2] = ((t204) * (t211) + (((t198) * (t212) + ((t201 * t213)))));
  J[2 * 7 + 3] = ((t204) * (t217) + (((t198) * (t215) + ((t201 * t216)))));
  J[2 * 7 + 4] = ((t204) * (t220) + (((t198) * (t222) + ((t201 * t223)))));
  J[2 * 7 + 5] = ((t204) * (t224) + (((t198) * (t225) + ((t201 * t226)))));
  J[3 * 7 + 0] = t202;
  J[3 * 7 + 1] = ((t196) * (r2) + ((t199 * r0)));
  J[3 * 7 + 2] = ((t202) * (r3) + (((t196) * (t174) + ((t199 * t176)))));
  J[3 * 7 + 3] = ((t202) * (t188) + (((t196) * (t182) + ((t199 * t185)))));
  J[3 * 7 + 4] = ((t202) * (t187) + (((t196) * (t181) + ((t199 * t184)))));
  J[3 * 7 + 5] = ((t202) * (t204) + (((t196) * (t198) + ((t199 * t201)))));
  J[4 * 7 + 0] = t203;
  J[4 * 7 + 1] = ((t197) * (r2) + ((t200 * r0)));
  J[4 * 7 + 2] = ((t203) * (r3) + (((t197) * (t174) + ((t200 * t176)))));
  J[4 * 7 + 3] = ((t203) * (t188) + (((t197) * (t182) + ((t200 * t185)))));
  J[4 * 7 + 4] = ((t203) * (t187) + (((t197) * (t181) + ((t200 * t184)))));
  J[4 * 7 + 5] = ((t203) * (t204) + (((t197) * (t198) + ((t200 * t201)))));
  J[5 * 7 + 0] = t204;
  J[5 * 7 + 1] = ((t198) * (r2) + ((t201 * r0)));
  J[5 * 7 + 2] = ((t204) * (r3) + (((t198) * (t174) + ((t201 * t176)))));
  J[5 * 7 + 3] = ((t204) * (t188) + (((t198) * (t182) + ((t201 * t185)))));
  J[5 * 7 + 4] = ((t204) * (t187) + (((t198) * (t181) + ((t201 * t184)))));
  J[5 * 7 + 5] = ((t204) * (t204) + (((t198) * (t198) + ((t201 * t201)))));
  }
}
#ifdef __cplusplus
}
#endif

