// Generated by fastfk for robot: ur3e_robot
// Task: spatial:upper_arm_link[0]; spatial:upper_arm_link[1]; spatial:upper_arm_link[2]; spatial:upper_arm_link[3]; spatial:upper_arm_link[4]; spatial:upper_arm_link[5]
#include "fk_jacobian.hpp"

// q-invariant R/p (call once; not written by fastfk_task).
void fastfk_init_static_frames(double* R, double* p) {
  // upper_arm_link
  R[8] = 0.0;
  p[0] = 0.0;
  p[1] = 0.0;
  p[2] = 0.15185000000000001;
}

#ifdef __cplusplus
extern "C" {
#endif
void fastfk_task(
    const double* q,
    double* R,
    double* p,
    double* J) {
  // frame: upper_arm_link
  {
  double fk_s42 = 0, fk_c41 = 0;
  fastfk_fast_sincos(q[0], &fk_s42, &fk_c41);
  const double r0 = fk_c41;
  const double t12 = (-(fk_s42));
  double fk_s48 = 0, fk_c47 = 0;
  fastfk_fast_sincos(q[1], &fk_s48, &fk_c47);
  const double t14 = fk_s48;
  const double t17 = (t12 * (-(t14)));
  const double r2 = ((-(r0)) * fk_c47);
  const double r3 = ((-(r0)) * (-(t14)));
  R[0] = r2;
  R[1] = r3;
  R[2] = t12;
  R[3] = (t12 * fk_c47);
  R[4] = t17;
  R[5] = r0;
  R[6] = t14;
  R[7] = fk_c47;
  // Jacobian (6 x 6)
  // q-dependent entries only; zero J before call (see fastfk_init_static_jacobian).
  J[3 * 6 + 0] = t14;
  J[3 * 6 + 1] = ((r2) * (t12) + (((t12 * fk_c47) * r0)));
  J[4 * 6 + 0] = fk_c47;
  J[4 * 6 + 1] = ((r3) * (t12) + ((t17 * r0)));
  J[5 * 6 + 1] = ((t12) * (t12) + ((r0 * r0)));
  }
}
#ifdef __cplusplus
}
#endif

